import { PrimaryButton } from '../../../components/PrimaryButton';
import type { DailyRawResult } from '../../../domain/assessment/results';
import type { LocalDateKey } from '../../../domain/progression/types';
import { matchSpatialMemoryPositions } from '../../../domain/scoring/normalizers';
import { visualSkinClass } from '../visualSkin';
import type { Day6TimerScheduler } from './useDay6SpatialMemoryAssessment';
import { useDay6SpatialMemoryAssessment } from './useDay6SpatialMemoryAssessment';

interface Props { sessionDateKey: LocalDateKey; onComplete: (result: Extract<DailyRawResult, { assessmentType: 'day6_spatial_memory' }>) => void; onDateInvalidated: () => void; dateNow?: () => Date; clock?: { now: () => number }; scheduler?: Day6TimerScheduler; createTrialId?: () => string; variationSessionId?: string }
const marker = (point: { x: number; y: number }, className: string, key: string) => <span key={key} className={className} style={{ left: `${point.x * 100}%`, top: `${point.y * 100}%` }} />;
const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
const conditionFor = (attemptIndex: number) => attemptIndex % 2 === 0 ? 'spread' : 'clustered';

function Masthead({ attempt }: { attempt: number }) { return <><header className="day2-ready-masthead"><span className="day2-ready-back" aria-hidden="true">‹</span><div><strong>DAY 6</strong><h1>순간 위치 기억</h1></div><span className="day2-ready-help" aria-hidden="true">?</span></header><ol className="day6-condition-progress" aria-label="DAY 6 진행 단계">{['INTRO', 'SPREAD', 'CLUSTERED', 'ANALYSIS'].map((label, index) => <li className={index === 0 || index < attempt ? 'is-complete' : index === attempt ? 'is-active' : 'is-pending'} key={label}><span>{index === 0 || index < attempt ? '✓' : ''}</span><strong>{label}</strong></li>)}</ol></> }
function ConditionCard({ condition, attempt }: { condition: 'spread' | 'clustered'; attempt: number }) { const spread = condition === 'spread'; return <section className={`day6-condition-card is-${condition}`}><span className="day6-memory-icon" aria-hidden="true"><i/><i/><i/></span><div><h2>{spread ? '퍼진 배치 · SPREAD' : '모인 배치 · CLUSTERED'}</h2><p>{spread ? '서로 떨어져 나타나는 세 위치를 기억합니다.' : '가까이 모여 나타나는 세 위치를 기억합니다.'}</p></div><aside><strong>{attempt} / 2</strong><small>측정 진행</small></aside></section> }
function FieldFrame({ children, className = '', ...props }: React.HTMLAttributes<HTMLElement>) { return <section {...props} className={`memory-stage day6-memory-field ${className}`}><span className="day6-field-corners" aria-hidden="true"/><span className="day6-field-reticle" aria-hidden="true"/>{children}</section> }

export function Day6SpatialMemoryAssessmentScreen(props: Props) {
  const assessment = useDay6SpatialMemoryAssessment(props), { phase, trials, lastTrial } = assessment;
  const attempt = Math.min(trials.length + 1, 2), condition = conditionFor(trials.length);
  if (phase === 'dateInvalidated' || phase === 'incomplete') return <div className="screen analysis-error"><section role="alert"><h1>{phase === 'dateInvalidated' ? '날짜가 변경되어 DAY 6를 다시 시작해야 합니다.' : '추가 분석을 완료하지 못했습니다.'}</h1><p>DAY 1~5 기록은 그대로 유지됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>DAY 6 다시 시작</PrimaryButton></div></div>;
  if (phase === 'exposure' || phase === 'blank' || phase === 'recall') { const copy = phase === 'exposure' ? ['OBSERVE', '나타난 세 위치를 기억해 주세요'] : phase === 'blank' ? ['WAIT', '방금 본 위치를 떠올려 주세요'] : ['RECALL', '기억나는 세 위치를 선택해 주세요']; return <div className={`screen day6-assessment-poster day6-running-poster is-${phase}`}><Masthead attempt={attempt}/><ConditionCard condition={condition} attempt={attempt}/><main><header><p>{copy[0]}</p><h2>{copy[1]}</h2>{phase === 'recall' && <span>선택 {assessment.selectedPositions.length} / 3</span>}</header><FieldFrame className={visualSkinClass(props.variationSessionId, 'day6_spatial_memory', trials.length)} role={phase === 'recall' ? 'application' : undefined} aria-label={phase === 'recall' ? '기억나는 위치를 선택하는 영역' : '위치를 기억하는 영역'} onPointerDown={(event) => assessment.selectPosition(event, event.currentTarget.getBoundingClientRect())}>{phase === 'exposure' && assessment.shownPositions.map((point, index) => marker(point, 'memory-target', `t${index}`))}{phase === 'recall' && assessment.selectedPositions.map((point, index) => marker(point, 'memory-selected', `s${index}`))}</FieldFrame><p className="day6-phase-note">{phase === 'exposure' ? '위치만 집중해서 관찰해 주세요.' : phase === 'blank' ? '화면이 비어 있는 동안 위치 표시는 없습니다.' : '기억만으로 화면을 세 번 눌러주세요.'}</p></main></div> }
  if (phase === 'result' && lastTrial) { const match = matchSpatialMemoryPositions(lastTrial), resultCondition = conditionFor(trials.length - 1); return <div className="screen day6-assessment-poster day6-result-poster"><Masthead attempt={Math.min(trials.length, 2)}/><ConditionCard condition={resultCondition} attempt={trials.length}/><main aria-live="polite">{lastTrial.valid && match ? <><header className="day6-result-heading"><span>✓</span><p>측정 완료</p><h2>평균 위치 오차 {pct(match.meanDistance)}</h2></header><FieldFrame className={`memory-result ${visualSkinClass(props.variationSessionId, 'day6_spatial_memory', trials.length - 1)}`} role="img" aria-label="실제 위치와 선택한 위치 및 최소 거리 짝을 비교합니다."><svg className="memory-match-lines" viewBox="0 0 100 100" aria-hidden="true">{match.permutation.map((selectedIndex, shownIndex) => <line key={shownIndex} x1={lastTrial.shownPositions[shownIndex]!.x * 100} y1={lastTrial.shownPositions[shownIndex]!.y * 100} x2={lastTrial.selectedPositions[selectedIndex]!.x * 100} y2={lastTrial.selectedPositions[selectedIndex]!.y * 100}/>)}</svg>{lastTrial.shownPositions.map((point, index) => marker(point, 'memory-target', `rt${index}`))}{lastTrial.selectedPositions.map((point, index) => marker(point, 'memory-selected', `rs${index}`))}</FieldFrame><div className="day6-result-legend"><span>실제 위치</span><span>선택 위치</span><span>최소 거리 매칭</span></div><p className="day6-result-note">실제 위치와 선택한 위치를 가장 가까운 전체 조합으로 비교했어요.</p></> : <><h2>이번 측정은 제외됩니다.</h2><p role="alert">화면 상태가 바뀌어 다시 측정해야 합니다.</p></>}</main><div className="day6-result-action"><PrimaryButton onClick={assessment.advanceFromResult}>{assessment.completion.status === 'completed' || assessment.completion.status === 'assessmentIncomplete' || assessment.completion.status === 'invalidAssessment' ? '결과 보기' : assessment.completion.status === 'retryAllowed' || !lastTrial.valid ? '다시 측정' : '다음 측정'}</PrimaryButton></div></div> }
  if (phase === 'complete') return <div className="screen summary-screen"><section className="summary-content"><p className="eyebrow">추가 측정 완료</p><h1>순간 위치 기억 측정을 마쳤습니다.</h1><p>멀리 떨어진 위치와 가까이 모인 위치의 기억 오차를 비교합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={() => props.onComplete({ assessmentType: 'day6_spatial_memory', trials })}>결과 확인</PrimaryButton></div></div>;
  return <div className="screen day6-assessment-poster day6-ready-poster"><Masthead attempt={1}/><ConditionCard condition="spread" attempt={1}/><main><header><p>오늘의 질문</p><h2>보고 난 위치를<br/>얼마나 정확히 기억할까?</h2><span>위치가 사라지면 기억한 곳을 세 번 선택합니다.</span></header><FieldFrame className="day6-preview" aria-hidden="true"><span className="day6-preview-dot a"/><span className="day6-preview-dot b"/><span className="day6-preview-dot c"/></FieldFrame><aside className="day6-ready-note"><strong>관찰 → 공백 → 회상</strong><p>미리보기의 장식점은 실제 측정 위치와 무관합니다.</p></aside></main><div className="day6-ready-action"><PrimaryButton onClick={assessment.startTrial}>측정 시작</PrimaryButton></div></div>;
}
