import { PrimaryButton } from '../../../components/PrimaryButton';
import type { DailyRawResult } from '../../../domain/assessment/results';
import { isDay6SpreadAttempt } from '../../../domain/assessment/day6SpatialMemoryConfig';
import type { LocalDateKey } from '../../../domain/progression/types';
import { matchSpatialMemoryPositions } from '../../../domain/scoring/normalizers';
import { InstrumentReadyContent, MemoryInstrument } from '../AssessmentInstruments';
import { visualSkinClass } from '../visualSkin';
import type { Day6TimerScheduler } from './useDay6SpatialMemoryAssessment';
import { useDay6SpatialMemoryAssessment } from './useDay6SpatialMemoryAssessment';

interface Props { sessionDateKey: LocalDateKey; onComplete: (r: Extract<DailyRawResult, { assessmentType: 'day6_spatial_memory' }>) => void; onDateInvalidated: () => void; dateNow?: () => Date; clock?: { now: () => number }; scheduler?: Day6TimerScheduler; createTrialId?: () => string; variationSessionId?: string }
const marker = (point: { x: number; y: number }, className: string, key: string) => <span aria-hidden="true" key={key} className={className} style={{ left: `${point.x * 100}%`, top: `${point.y * 100}%` }} />;
const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
const condition = (attempt: number) => isDay6SpreadAttempt(attempt) ? { ko: '넓은 배치', en: 'SPREAD' } : { ko: '밀집 배치', en: 'CLUSTERED' };
const phaseCopy = { exposure: { en: 'OBSERVE', ko: '위치를 확인하세요' }, blank: { en: 'MEMORY HOLD', ko: '위치를 기억하세요' }, recall: { en: 'RECALL', ko: '기억한 위치를 선택하세요' } } as const;

function MemoryFrame({ phase, attempt, children }: { phase: keyof typeof phaseCopy; attempt: number; children: React.ReactNode }) {
  const current = condition(attempt), copy = phaseCopy[phase];
  return <section className={`day6-memory-field is-${phase}`} aria-labelledby="day6-memory-state"><div className="memory-state-strip"><div><span>{copy.en}</span><strong id="day6-memory-state">{copy.ko}</strong></div><p><span>{current.ko}</span><b>{current.en}</b></p></div><div className="memory-register" aria-hidden="true"><i/><i/><i/><i/></div>{children}</section>;
}

export function Day6SpatialMemoryAssessmentScreen(props: Props) {
  const a = useDay6SpatialMemoryAssessment(props), { phase, trials, lastTrial } = a;
  const attempt = trials.length;
  if (phase === 'dateInvalidated') return <div className="screen analysis-error"><section role="alert"><h1>날짜가 변경되어 DAY 6를 다시 시작해야 합니다.</h1><p>DAY 1~5 기록은 그대로 유지됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>DAY 6 다시 시작</PrimaryButton></div></div>;
  if (phase === 'incomplete') return <div className="screen analysis-error"><section role="alert"><h1>추가 분석을 완료하지 못했습니다.</h1><p>DAY 6만 처음부터 다시 측정합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>처음부터 다시</PrimaryButton></div></div>;
  if (phase === 'exposure' || phase === 'blank' || phase === 'recall') return <div className={`screen day6-memory-screen day6-memory-${phase}`}><header className="progress-header"><span>DAY 6 · 순간 위치 기억</span><span>{trials.length < 2 ? `${trials.length + 1} / 2` : `추가 측정 ${trials.length - 1}`}</span></header><MemoryFrame phase={phase} attempt={attempt}><div className={`memory-stage ${visualSkinClass(props.variationSessionId, 'day6_spatial_memory', trials.length)}`} role={phase === 'recall' ? 'application' : undefined} aria-label={phase === 'recall' ? '기억나는 위치를 선택하는 영역' : '위치를 기억하는 영역'} onPointerDown={(event) => a.selectPosition(event, event.currentTarget.getBoundingClientRect())}>{phase === 'exposure' && a.shownPositions.map((point, index) => marker(point, 'memory-target', `t${index}`))}{phase === 'recall' && a.selectedPositions.map((point, index) => marker(point, 'memory-selected', `s${index}`))}<p>{phase === 'exposure' ? '세 위치를 확인해 주세요.' : phase === 'blank' ? '화면이 비워졌습니다.' : `선택 ${a.selectedPositions.length} / 3`}</p></div></MemoryFrame></div>;
  if (phase === 'result' && lastTrial) {
    const match = matchSpatialMemoryPositions(lastTrial), current = condition(trials.length - 1);
    return <div className="screen result-screen day6-memory-result-screen"><header className="progress-header"><span>DAY 6 · 순간 위치 기억</span><span>{Math.min(trials.length, 2)} / 2</span></header><section className="trial-result" aria-live="polite"><div className="memory-result-heading"><div><span>MEMORY RECONSTRUCTION</span><strong>회상 비교</strong></div><p>{current.ko} · {current.en}</p></div>{lastTrial.valid && match ? <><div className={`memory-stage memory-result ${visualSkinClass(props.variationSessionId, 'day6_spatial_memory', trials.length - 1)}`} role="img" aria-label="실제 위치와 선택한 위치 및 최소 거리 짝을 비교합니다."><svg className="memory-match-lines" viewBox="0 0 100 100" aria-hidden="true">{match.permutation.map((selectedIndex, shownIndex) => <line key={shownIndex} x1={lastTrial.shownPositions[shownIndex]!.x * 100} y1={lastTrial.shownPositions[shownIndex]!.y * 100} x2={lastTrial.selectedPositions[selectedIndex]!.x * 100} y2={lastTrial.selectedPositions[selectedIndex]!.y * 100} />)}</svg>{lastTrial.shownPositions.map((point, index) => marker(point, 'memory-target', `rt${index}`))}{lastTrial.selectedPositions.map((point, index) => marker(point, 'memory-selected', `rs${index}`))}</div><div className="memory-result-legend" aria-label="회상 비교 범례"><span>실제 위치</span><span>선택 위치</span><span>최소 거리 짝</span></div><p className="memory-result-metric">위치 기억 오차</p><h1>평균 {pct(match.meanDistance)}</h1><p>실제 위치와 선택한 위치를 가장 가까운 전체 조합으로 비교했어요.</p></> : <><h1>이번 측정은 제외됩니다.</h1><p role="alert">화면 상태가 바뀌어 다시 측정해야 합니다.</p></>}</section><div className="bottom-action"><PrimaryButton onClick={a.advanceFromResult}>{a.completion.status === 'completed' || a.completion.status === 'assessmentIncomplete' || a.completion.status === 'invalidAssessment' ? '결과 보기' : a.completion.status === 'retryAllowed' || !lastTrial.valid ? '다시 측정' : '다음 측정'}</PrimaryButton></div></div>;
  }
  if (phase === 'complete') return <div className="screen summary-screen"><section className="summary-content"><p className="eyebrow">추가 측정 완료</p><h1>순간 위치 기억 측정을 마쳤습니다.</h1><p>멀리 떨어진 위치와 가까이 모인 위치의 기억 오차를 비교합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={() => props.onComplete({ assessmentType: 'day6_spatial_memory', trials })}>결과 확인</PrimaryButton></div></div>;
  const first = condition(0);
  return <div className="screen ready-screen day6-memory-ready"><header className="progress-header"><span>DAY 6 · 순간 위치 기억</span><span>1 / 2</span></header><div className="day6-ready-masthead"><div><span>SPATIAL MEMORY</span><strong>보고 난 위치를 얼마나 정확히 기억할까?</strong></div><p>{first.ko} · {first.en}</p></div><div className="memory-process" aria-label="순간 위치 기억 측정 과정"><div><span>01 · OBSERVE</span><strong>위치를 확인하고</strong></div><i aria-hidden="true">→</i><div><span>02 · CLEAR</span><strong>화면이 비워진 뒤</strong></div><i aria-hidden="true">→</i><div><span>03 · RECALL</span><strong>기억한 위치를 선택합니다</strong></div></div><InstrumentReadyContent instrument={<MemoryInstrument />} title="잠깐 나타나는 세 위치를 기억해 주세요.">위치가 사라진 뒤 같은 곳을 세 번 선택합니다.</InstrumentReadyContent><div className="bottom-action"><PrimaryButton onClick={a.startTrial}>측정 시작</PrimaryButton></div></div>;
}
