$ErrorActionPreference = 'Stop'
$target = (Invoke-RestMethod 'http://127.0.0.1:9333/json/list').Where({ $_.type -eq 'page' }, 'First')[0]
$socket = [System.Net.WebSockets.ClientWebSocket]::new(); $socket.ConnectAsync([Uri]$target.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult(); $script:id=0
function Send-Cdp($method,$params){$script:id++;$requestId=$script:id;$json=@{id=$requestId;method=$method;params=$params}|ConvertTo-Json -Depth 8 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($json);$socket.SendAsync([ArraySegment[byte]]$bytes,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult();while($true){$stream=[IO.MemoryStream]::new();do{$buffer=New-Object byte[] 1048576;$result=$socket.ReceiveAsync([ArraySegment[byte]]$buffer,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$stream.Write($buffer,0,$result.Count)}while(-not $result.EndOfMessage);$response=[Text.Encoding]::UTF8.GetString($stream.ToArray())|ConvertFrom-Json;if($response.id -eq $requestId){return $response}}}
function Eval($expression){Send-Cdp 'Runtime.evaluate' @{expression=$expression}|Out-Null;Start-Sleep -Milliseconds 220}
function Capture($width,$height,$name){Send-Cdp 'Emulation.setDeviceMetricsOverride' @{width=$width;height=$height;deviceScaleFactor=1;mobile=$true}|Out-Null;Start-Sleep -Milliseconds 180;$shot=Send-Cdp 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes("C:\Users\user\Downloads\$name",[Convert]::FromBase64String($shot.result.data))}
Eval "document.querySelectorAll('.focus-item')[1].click()"; Eval "document.querySelector('.focus-screen.result-screen .bottom-action button').click()"; Capture 360 800 'focus-running-config2-360x800.png'
Eval "document.querySelectorAll('.focus-item')[7].click()"; Eval "document.querySelector('.focus-screen.result-screen .bottom-action button').click()"; Capture 412 786 'focus-running-config3-412x786.png'
$socket.Dispose()
