import { render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import { deriveAnalysis } from '../../domain/scoring/deriveAnalysis';
import type { DailyRecord, PersistedAppData } from '../../domain/storage/types';
import { baselineFixture } from '../../test/day1Fixture';
import { Day3AnalysisScreen } from './Day3AnalysisScreen';
const d2: DailyRecord = { recordId:'d2',sessionId:'d2',analysisDay:2,assessmentType:'day2_time_distraction',startedAt:'2026-08-13T01:00:00Z',completedAt:'2026-08-13T01:01:00Z',localDateKey:'2026-08-13',rawResult:{assessmentType:'day2_time_distraction',trials:['plain','distracted','plain','distracted'].map((condition,index)=>({kind:'timeCondition' as const,condition:condition as 'plain'|'distracted',targetDurationMs:3000 as const,observedDurationMs:3000,trialId:`t${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}};
const record = (points: readonly [{x:number;y:number},{x:number;y:number},{x:number;y:number}]): DailyRecord => ({ recordId:'d3',sessionId:'d3',analysisDay:3,assessmentType:'day3_decorated_center',startedAt:'2026-08-14T01:00:00Z',completedAt:'2026-08-14T01:01:00Z',localDateKey:'2026-08-14',rawResult:{assessmentType:'day3_decorated_center',trials:(['plain','decoratedLeft','decoratedRight'] as const).map((condition,index)=>({kind:'centerCondition' as const,condition,decorationSide:(['none','left','right'] as const)[index]!,stimulusId:(['day3-plain-01','day3-left-01','day3-right-01'] as const)[index]!,target:{x:.5,y:.5},observed:points[index]!,trialId:`c${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}});
const root: PersistedAppData = { schemaVersion:1,baseline:baselineFixture,dailyRecords:[d2],metadata:{} };
function show(day3: DailyRecord) { const before=deriveAnalysis(root),after=deriveAnalysis({...root,dailyRecords:[d2,day3]}); if(!before.ok||!after.ok)throw new Error('fixture'); render(<Day3AnalysisScreen baseline={baselineFixture} record={day3} before={before.value} after={after.value} saveStatus="saved" onHome={()=>undefined}/>); return {before:before.value,after:after.value}; }
describe('Day3AnalysisScreen',()=>{
  it('eligible neutral을 임의 방향 없이 표시한다',()=>{const values=show(record([{x:.5,y:.5},{x:.7,y:.7},{x:.3,y:.3}]));expect(values.after.tendencies.find(t=>t.key==='visualBias')).toMatchObject({eligible:true,direction:'neutral'});expect(screen.getByText(/한쪽 방향으로 뚜렷하게 끌리지는/)).toBeInTheDocument();expect(screen.queryByText(/오른쪽 방향으로 이동/)).not.toBeInTheDocument();});
  it('DAY 3 plain과 장식 근거, magnitude, Center secondary와 다른 Ability 불변을 표시한다',()=>{const values=show(record([{x:.5,y:.5},{x:.7,y:.52},{x:.7,y:.52}]));expect(screen.getByText('무장식')).toBeInTheDocument();expect(screen.getByText('DAY 3 plain 평균 중심 오차')).toBeInTheDocument();expect(screen.getByText('시각 유도')).toBeInTheDocument();expect(screen.getByText(/오른쪽 · 20.1%/)).toBeInTheDocument();expect(screen.getByRole('heading',{name:'중심 감각 점수'}).closest('section')).toHaveClass('score-secondary');expect(values.after.scores.time).toBe(values.before.scores.time);expect(values.after.scores.balance).toBe(values.before.scores.balance);expect(values.after.scores.control).toBe(values.before.scores.control);expect(values.after.scores.focus).toBe(values.before.scores.focus);expect(screen.getByText('심화 분석 2/5')).toBeInTheDocument();});
  it('diagram과 legend의 세 marker identity를 일치시키고 raw 좌표를 offset 없이 style에 쓴다',()=>{show(record([{x:.5,y:.5},{x:.7,y:.52},{x:.7,y:.52}]));const diagram=screen.getByRole('img',{name:'중심 비교 다이어그램. DAY 1 평균 위치, DAY 3 장식 조건 평균 위치, 실제 중심 위치를 비교합니다.'});const baseline=diagram.querySelector('.diagram-baseline');const day3=diagram.querySelector('.diagram-day3');const truth=diagram.querySelector('.diagram-true');expect(baseline).toHaveAttribute('style','left: 51%; top: 50%;');expect(day3).toHaveAttribute('style','left: 70%; top: 52%;');expect(truth).not.toHaveAttribute('style');expect(screen.getByText('DAY 1 평균')).toHaveClass('day3-legend-baseline');expect(screen.getByText('DAY 3 장식 평균')).toHaveClass('day3-legend-day3');expect(screen.getByText('실제 중심')).toHaveClass('day3-legend-true');});
  it('같거나 가까운 좌표 fixture에서도 세 marker class와 실제 좌표를 그대로 유지한다',()=>{show(record([{x:.5,y:.5},{x:.5,y:.5},{x:.5,y:.5}]));const diagram=screen.getByRole('img');expect(diagram.querySelector('.diagram-baseline')).toHaveAttribute('style','left: 51%; top: 50%;');expect(diagram.querySelector('.diagram-day3')).toHaveAttribute('style','left: 50%; top: 50%;');expect(diagram.querySelector('.diagram-true')).not.toHaveAttribute('style');});
});
