import { render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import { deriveAnalysis } from '../../domain/scoring/deriveAnalysis';
import type { DailyRecord, PersistedAppData } from '../../domain/storage/types';
import { baselineFixture } from '../../test/day1Fixture';
import { Day4AnalysisScreen } from './Day4AnalysisScreen';
const d2:DailyRecord={recordId:'d2',sessionId:'d2',analysisDay:2,assessmentType:'day2_time_distraction',startedAt:'2026-08-13T01:00:00Z',completedAt:'2026-08-13T01:01:00Z',localDateKey:'2026-08-13',rawResult:{assessmentType:'day2_time_distraction',trials:['plain','distracted','plain','distracted'].map((condition,index)=>({kind:'timeCondition' as const,condition:condition as 'plain'|'distracted',targetDurationMs:3000 as const,observedDurationMs:3000,trialId:`t${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}};
const d3:DailyRecord={recordId:'d3',sessionId:'d3',analysisDay:3,assessmentType:'day3_decorated_center',startedAt:'2026-08-14T01:00:00Z',completedAt:'2026-08-14T01:01:00Z',localDateKey:'2026-08-14',rawResult:{assessmentType:'day3_decorated_center',trials:(['plain','decoratedLeft','decoratedRight'] as const).map((condition,index)=>({kind:'centerCondition' as const,condition,decorationSide:(['none','left','right'] as const)[index]!,stimulusId:(['day3-plain-01','day3-left-01','day3-right-01'] as const)[index]!,target:{x:.5,y:.5},observed:{x:.5,y:.5},trialId:`c${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}};
const makeDay4=(cuts:readonly [[number,number],[number,number]]):DailyRecord=>({recordId:'d4',sessionId:'d4',analysisDay:4,assessmentType:'day4_balance_three_way',startedAt:'2026-08-15T01:00:00Z',completedAt:'2026-08-15T01:01:00Z',localDateKey:'2026-08-15',rawResult:{assessmentType:'day4_balance_three_way',trials:cuts.map((cutPositions,index)=>({kind:'balanceThreeWay' as const,cutPositions,trialId:`b${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}});
const root:PersistedAppData={schemaVersion:1,baseline:baselineFixture,dailyRecords:[d2,d3],metadata:{}};
function show(record:DailyRecord){const before=deriveAnalysis(root),after=deriveAnalysis({...root,dailyRecords:[...root.dailyRecords,record]});if(!before.ok||!after.ok)throw new Error('fixture');render(<Day4AnalysisScreen baseline={baselineFixture} record={record} before={before.value} after={after.value} saveStatus="saved" onHome={()=>undefined}/>);return{before:before.value,after:after.value};}
describe('Day4AnalysisScreen',()=>{
  it('QA fixture는 degradation을 primary로 두고 미세 terminal sign을 방향으로 단정하지 않는다',()=>{const values=show(makeDay4([[.28,.72],[.38,.62]]));expect(screen.getByRole('heading',{name:/균형 판단이 조금 더 흔들리는 편/})).toBeInTheDocument();expect(screen.queryByText(/마지막 구간을 조금 작게 남기는 편/)).not.toBeInTheDocument();expect(screen.getByText(/뚜렷하게 한쪽을 크게 또는 작게 남기는 편향은 없었어요/)).toBeInTheDocument();expect(screen.getByText('33.0% | 34.0% | 33.0%')).toBeInTheDocument();expect(values.before.scores.balance).toBe(93);expect(values.after.scores.balance).toBe(91);});
  it('strong negative terminal component는 마지막 구간 작게로 표시한다',()=>{show(makeDay4([[.30,.75],[.30,.75]]));expect(screen.getByText('마지막 구간을 조금 작게 남기는 편이에요.')).toBeInTheDocument();});
  it('strong positive terminal component는 마지막 구간 크게로 표시한다',()=>{show(makeDay4([[.20,.60],[.20,.60]]));expect(screen.getByText('마지막 구간을 조금 크게 남기는 편이에요.')).toBeInTheDocument();});
  it('반대 방향 trial과 평균을 함께 보여 상쇄 관계를 설명하고 다른 Ability는 유지한다',()=>{const values=show(makeDay4([[.28,.72],[.38,.62]]));expect(screen.getByText('28.0% | 44.0% | 28.0%')).toBeInTheDocument();expect(screen.getByText('38.0% | 24.0% | 38.0%')).toBeInTheDocument();expect(screen.getByText(/시도마다 다른 방향으로 흔들린 부분/)).toBeInTheDocument();expect(screen.getByRole('heading',{name:'균형 분배 점수'}).closest('section')).toHaveClass('score-secondary');expect(values.after.scores.time).toBe(values.before.scores.time);expect(values.after.scores.center).toBe(values.before.scores.center);expect(values.after.scores.control).toBe(values.before.scores.control);expect(values.after.scores.focus).toBe(values.before.scores.focus);expect(screen.getByText('심화 분석 3/5')).toBeInTheDocument();});
});
