import { DailyDiscoveryPanel } from '../../components/DailyDiscoveryPanel';
import { PrimaryButton } from '../../components/PrimaryButton';
import type { BalanceThreeWayTrial,BalanceTwoWayTrial } from '../../domain/assessment/trials';
import { threeWayError,twoWayError } from '../../domain/scoring/normalizers';
import type { DerivedAnalysis } from '../../domain/scoring/types';
import type { BaselineRecord,DailyRecord } from '../../domain/storage/types';
import { day4Segments } from '../assessment/day4Balance/day4BalanceConfig';
import { deriveTerminalDirection,hasCancellationAcrossTrials,hasMeaningfulThreeWayDegradation } from './day4Presentation';
interface Props{baseline:BaselineRecord;record:DailyRecord;before:DerivedAnalysis;after:DerivedAnalysis;saveStatus:'saving'|'saved'|'failed';onRetrySave?:()=>void;onHome?:()=>void;onAnalysis?:()=>void}
const mean=(values:readonly number[])=>values.reduce((sum,value)=>sum+value,0)/values.length;const pct=(value:number,digits=1)=>`${(value*100).toFixed(digits)}%`;
export function Day4AnalysisScreen({baseline,record,before,after,saveStatus,onRetrySave,onHome,onAnalysis}:Props){
 const baselineResult=baseline.assessmentRawResults.find(result=>result.assessmentType==='day1_balance_two_way');
 const baselineTrials=baselineResult?.assessmentType==='day1_balance_two_way'?baselineResult.trials.filter((trial):trial is Extract<BalanceTwoWayTrial,{valid:true}>=>trial.valid):[];
 const day4Trials=record.rawResult.assessmentType==='day4_balance_three_way'?record.rawResult.trials.filter((trial):trial is Extract<BalanceThreeWayTrial,{valid:true}>=>trial.valid):[];
 if(!baselineTrials.length||day4Trials.length<2)return <div className="screen analysis-error"><section role="alert"><h1>분석에 필요한 기록을 계산하지 못했습니다.</h1></section></div>;
 const twoWayMean=mean(baselineTrials.map(twoWayError).filter((value):value is number=>value!==null));const errors=day4Trials.map(threeWayError).filter((value):value is number=>value!==null);const threeWayMean=mean(errors);const trialSegments=day4Trials.map(trial=>day4Segments(trial.cutPositions));const averageSegments=[0,1,2].map(index=>mean(trialSegments.map(segments=>segments[index]!)));const terminalDirection=deriveTerminalDirection(averageSegments[2]!-1/3);const degradationEligible=hasMeaningfulThreeWayDegradation(twoWayMean,threeWayMean);const cancellation=hasCancellationAcrossTrials(trialSegments);const headline=degradationEligible?'세 조각으로 나누면 균형 판단이 조금 더 흔들리는 편':'세 조각으로 늘어나도 균형 감각은 꽤 안정적인 편';const terminalCopy=terminalDirection==='large'?'마지막 구간을 조금 크게 남기는 편이에요.':terminalDirection==='small'?'마지막 구간을 조금 작게 남기는 편이에요.':'세 구간에서 뚜렷하게 한쪽을 크게 또는 작게 남기는 편향은 없었어요.';
 return <div className="screen analysis-screen daily-analysis day4-analysis day4-analysis-poster"><header className="analysis-record-header"><span>쓸능검 · 복합 분배 리포트</span><span>DAY 4</span></header><main><section className="analysis-hero"><p className="eyebrow">복잡해지면 균형 감각도 달라질까?</p><h1>{headline}</h1><span className="analysis-chip">분석 완료</span></section><section className="report-section"><div className="section-index">01 · COMPLEXITY EVIDENCE</div><h2>2등분과 3등분 안정성</h2><div className="condition-cards"><div><span>DAY 1 · 2등분</span><strong>{pct(twoWayMean)}</strong><small>평균 분배 오차</small></div><div><span>DAY 4 · 3등분</span><strong>{pct(threeWayMean)}</strong><small>평균 분배 오차</small></div></div><div className="condition-delta"><span>복잡도 변화</span><strong>{degradationEligible?'3등분에서 오차 증가':'큰 차이 없음'}</strong></div></section><section className="report-section"><div className="section-index">02 · TRIAL EVIDENCE</div><h2>두 시도의 실제 분배</h2><div className="day4-analysis-trials">{trialSegments.map((segments,index)=><div key={day4Trials[index]!.trialId}><span>{index+1}회차 · 평균 오차 {pct(errors[index]!)}</span><strong>{segments.map(value=>pct(value)).join(' | ')}</strong></div>)}<div><span>내 평균</span><strong>{averageSegments.map(value=>pct(value)).join(' | ')}</strong><small>같은 분배 기준 · 33.3% | 33.3% | 33.3%</small></div></div>{cancellation&&<p>평균 분배는 비슷했지만, 시도마다 다른 방향으로 흔들린 부분이 있었어요.</p>}</section><section className="report-section"><div className="section-index">03 · INTERPRETATION</div><h2>짧은 해석</h2><p>{terminalCopy}</p></section><section className="report-section score-secondary"><div className="section-index">04 · BALANCE SCORE</div><h2>BALANCE 능력 변화</h2><p className="score-change">{before.scores.balance} → {after.scores.balance}</p>{before.scores.balance===after.scores.balance&&<p>균형 분배 점수는 그대로 유지됐어요.</p>}<p>기존 scoring 결과이며 다른 능력 점수는 유지합니다.</p></section><DailyDiscoveryPanel day={4} totalDays={7} insight={headline} nextTeaser="예상 밖 변화에서도 손가락 통제가 유지될까?"/>{saveStatus==='saving'&&<p role="status" className="storage-status">추가 분석을 기기에 저장하고 있습니다.</p>}{saveStatus==='failed'&&<div role="alert" className="storage-warning"><p>추가 분석을 저장하지 못했습니다. 측정 결과는 그대로 유지됩니다.</p>{onRetrySave&&<button className="secondary-button" onClick={onRetrySave}>다시 저장</button>}</div>}<div className="analysis-actions"><PrimaryButton disabled={!onHome} onClick={onHome}>분석 결과 확인 완료</PrimaryButton>{onAnalysis&&<button className="secondary-button" onClick={onAnalysis}>업데이트된 분석서 보기</button>}</div></main></div>;
}
