import { render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import type { DerivedAnalysis } from '../../domain/scoring/types';
import type { DailyRecord } from '../../domain/storage/types';
import { Day5AnalysisScreen } from './Day5AnalysisScreen';
const analysis=(control:number,eligible:boolean,direction='degraded')=>({scores:{time:90,center:90,balance:90,control,focus:90},tendencies:[{key:'surpriseSensitivity',eligible,magnitude:eligible?.4:.01,direction,contentKey:'control.surprise',supportingEvidence:['day5_control_surprise']}]} as unknown as DerivedAnalysis);
const record=(predictable:number,surprise:number):DailyRecord=>({recordId:'d5',sessionId:'d5',analysisDay:5,assessmentType:'day5_control_surprise',startedAt:'2026-08-16T01:00:00Z',completedAt:'2026-08-16T01:01:00Z',localDateKey:'2026-08-16',rawResult:{assessmentType:'day5_control_surprise',trials:[['predictable',.58,predictable,.32,.32,null],['surprise',.58,surprise,.32,.5,.45],['predictable',.68,.68+predictable-.58,.4,.4,null],['surprise',.68,.68+surprise-.58,.4,.24,.5]].map(([condition,targetPosition,observedPosition,initialSpeedNormalized,finalSpeedNormalized,speedChangeAtNormalizedTime],index)=>({kind:'controlCondition' as const,condition:condition as 'predictable'|'surprise',targetPosition:Number(targetPosition),observedPosition:Number(observedPosition),initialSpeedNormalized:Number(initialSpeedNormalized),finalSpeedNormalized:Number(finalSpeedNormalized),speedChangeAtNormalizedTime:speedChangeAtNormalizedTime===null?null:Number(speedChangeAtNormalizedTime),trialId:`c${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}});
describe('Day5AnalysisScreen',()=>{
  it('predictable/surprise 오차 증가를 primary로, Control score를 secondary로 표시한다',()=>{render(<Day5AnalysisScreen record={record(.59,.64)} before={analysis(94,false)} after={analysis(90,true)} saveStatus="saved" onHome={vi.fn()}/>);expect(screen.getByRole('heading',{name:'예상이 깨지면 정지 오차가 커지는 편'})).toBeInTheDocument();expect(screen.getByText('1.0%')).toBeInTheDocument();expect(screen.getByText('6.0%')).toBeInTheDocument();expect(screen.getByText('+5.0%p')).toBeInTheDocument();expect(screen.getByText('오차 증가')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'손가락 통제 점수'}).closest('section')).toHaveClass('score-secondary');expect(screen.getByText('94 → 90')).toBeInTheDocument();expect(screen.getByText('심화 분석 4/5')).toBeInTheDocument();});
  it('eligibility 미달이면 통제력 유지 copy와 score unchanged를 표시한다',()=>{render(<Day5AnalysisScreen record={record(.59,.59)} before={analysis(94,false)} after={analysis(94,false)} saveStatus="saved"/>);expect(screen.getByRole('heading',{name:'갑작스러운 변속에도 통제력은 거의 그대로'})).toBeInTheDocument();expect(screen.getByText('손가락 통제 점수는 그대로 유지됐어요.')).toBeInTheDocument();});
  it('eligibility 미달의 nonzero delta도 변화 거의 없음으로 표시한다',()=>{render(<Day5AnalysisScreen record={record(.59,.592)} before={analysis(94,false)} after={analysis(94,false)} saveStatus="saved"/>);expect(screen.getByText('변화 거의 없음')).toBeInTheDocument();expect(screen.getByText('+0.2%p')).toBeInTheDocument();expect(screen.queryByText('오차 증가')).not.toBeInTheDocument();});
  it('V1 consistency contradiction 설명을 표시하지 않는다',()=>{render(<Day5AnalysisScreen record={record(.59,.64)} before={analysis(90,false)} after={analysis(88,true)} saveStatus="saved"/>);expect(screen.queryByText('점수는 정확도뿐 아니라 측정 일관성도 함께 반영해요.')).not.toBeInTheDocument();});
});
