import { DailyDiscoveryPanel } from '../../components/DailyDiscoveryPanel';
import { PrimaryButton } from '../../components/PrimaryButton';
import { isDay6SpreadAttempt } from '../../domain/assessment/day6SpatialMemoryConfig';
import type { SpatialMemoryTrial } from '../../domain/assessment/trials';
import { matchingMeanDistance } from '../../domain/scoring/normalizers';
import type { DerivedAnalysis } from '../../domain/scoring/types';
import type { DailyRecord } from '../../domain/storage/types';
interface Props { record: DailyRecord; before: DerivedAnalysis; after: DerivedAnalysis; saveStatus: 'saving' | 'saved' | 'failed'; onRetrySave?: () => void; onHome?: () => void; onAnalysis?: () => void }
const mean = (values: readonly number[]) => values.reduce((sum, value) => sum + value, 0) / values.length, pct = (value: number) => `${(value * 100).toFixed(1)}%`, delta = (value: number) => `${value >= 0 ? '+' : ''}${(value * 100).toFixed(1)}%p`;
export function Day6AnalysisScreen({ record, before, after, saveStatus, onRetrySave, onHome, onAnalysis }: Props) {
  const indexed = record.rawResult.assessmentType === 'day6_spatial_memory' ? record.rawResult.trials.map((trial, attemptIndex) => ({ trial, attemptIndex })) : [];
  const errors = (spread: boolean) => indexed.flatMap(({ trial, attemptIndex }) => trial.valid && isDay6SpreadAttempt(attemptIndex) === spread ? [matchingMeanDistance(trial as Extract<SpatialMemoryTrial, { valid: true }>)!] : []), spread = errors(true), clustered = errors(false);
  if (!spread.length || !clustered.length) return <div className="screen analysis-error"><section role="alert"><h1>분석에 필요한 기록을 계산하지 못했습니다.</h1></section></div>;
  const spreadMean = mean(spread), clusteredMean = mean(clustered), change = clusteredMean - spreadMean, eligible = Boolean(after.tendencies.find((item) => item.key === 'spatialMemorySupport')?.eligible);
  const headline = !eligible ? '위치가 가까워져도 기억 정확도는 거의 그대로였어요.' : change > 0 ? '위치가 서로 가까워지면 기억 지점이 조금 더 흔들리는 편' : '위치가 가까이 모여도 기억 지점은 더 정확한 편';
  const interpretation = !eligible ? '퍼진 배치와 모인 배치에서 비슷한 위치 기억 결과를 보였습니다.' : change > 0 ? '위치가 가까이 모인 조건에서 평균 위치 오차가 더 커졌습니다.' : '위치가 가까이 모여도 평균 위치 오차가 크게 늘지 않았습니다.';
  return <div className="screen analysis-screen daily-analysis day6-analysis day6-analysis-poster"><header className="analysis-record-header"><span>쓸능검 · 위치 기억 리포트</span><span>DAY 6</span></header><main><section className="analysis-hero"><p className="eyebrow">보고 난 위치를 얼마나 정확히 기억할까?</p><h1>{headline}</h1><span className="analysis-chip">분석 완료</span></section><section className="report-section"><div className="section-index">01 · CONDITION EVIDENCE</div><h2>배치 간격에 따른 기억 비교</h2><div className="condition-cards"><div><span>멀리 떨어진 위치</span><strong>{pct(spreadMean)}</strong><small>평균 위치 오차</small></div><div><span>가까이 모인 위치</span><strong>{pct(clusteredMean)}</strong><small>평균 위치 오차</small></div></div><div className="condition-delta"><span>{!eligible ? '변화 거의 없음' : change > 0 ? '오차 증가' : change < 0 ? '오차 감소' : '변화 없음'}</span><strong>{delta(change)}</strong></div></section><section className="report-section"><div className="section-index">02 · TRIAL EVIDENCE</div><h2>조건별 실제 매칭 오차</h2><div className="day6-analysis-trials"><div><span>SPREAD</span><strong>{spread.map(pct).join(' · ')}</strong></div><div><span>CLUSTERED</span><strong>{clustered.map(pct).join(' · ')}</strong></div></div></section><section className="report-section"><div className="section-index">03 · INTERPRETATION</div><h2>짧은 해석</h2><p>{interpretation}</p></section><section className="report-section score-secondary"><div className="section-index">04 · FOCUS SCORE</div><h2>FOCUS 능력 변화</h2><p className="score-change">{before.scores.focus} → {after.scores.focus}</p>{before.scores.focus === after.scores.focus && <p>시각 집중 점수는 그대로 유지됐어요.</p>}<p>기존 scoring 결과이며 다른 능력 점수는 유지합니다.</p></section><DailyDiscoveryPanel day={6} totalDays={7} insight={headline} nextTeaser="가장 애매했던 능력을 마지막으로 다시 확인합니다."/>{saveStatus === 'saving' && <p role="status" className="storage-status">추가 분석을 기기에 저장하고 있습니다.</p>}{saveStatus === 'failed' && <div role="alert" className="storage-warning"><p>추가 분석을 저장하지 못했습니다. 측정 결과는 그대로 유지됩니다.</p>{onRetrySave && <button className="secondary-button" onClick={onRetrySave}>다시 저장</button>}</div>}<div className="analysis-actions"><PrimaryButton disabled={!onHome} onClick={onHome}>분석 결과 확인 완료</PrimaryButton>{onAnalysis && <button className="secondary-button" onClick={onAnalysis}>업데이트된 분석서 보기</button>}</div></main></div>;
}
