import type { PersistedAppData } from '../storage/types';
import { CALIBRATION_VERSION } from './calibration'; import { selectCertifications } from './certification'; import { selectCrossInsights } from './crossInsights'; import { conditionMagnitudes, mostConditionSensitive, mostPositivelyUpdated, mostStable } from './finalMetrics'; import { selectProfile } from './profile'; import { applyFinalScore, finalEquivalent, scoreBaseline } from './scores'; import { calculateStability } from './stability'; import { deriveTendencies, selectDominantTendency } from './tendencies'; import { ABILITIES, type Ability, type DeriveAnalysisResult } from './types';
import { deriveOverallScore, OVERALL_SCORE_VERSION } from './overall';
import { applyDailyModifier, deriveDailyModifier } from './dailyModifier';
export function deriveAnalysis(data: PersistedAppData): DeriveAnalysisResult {
  if (!data.baseline) return { ok: false, reason: 'insufficientEvidence' };
  const baselineRaw = data.baseline.assessmentRawResults; const baseline = scoreBaseline(baselineRaw); if (!baseline.ok) return baseline;
  const scores = { ...baseline.value }; let previous = { ...scores }; const sorted = [...data.dailyRecords].sort((a, b) => a.analysisDay - b.analysisDay); const dailyRaw = sorted.map((record) => record.rawResult);
  const baselineStability = calculateStability(baselineRaw, []); let profile = selectProfile(null, scores, scores, baselineStability, null);
  for (const [index, record] of sorted.entries()) { const modifier = deriveDailyModifier(baselineRaw, record.rawResult); if (!modifier.ok) return modifier; previous = { ...scores }; scores[modifier.value.ability] = applyDailyModifier(baseline.value[modifier.value.ability], modifier.value.delta); const partial = dailyRaw.slice(0, index + 1); const stability = calculateStability(baselineRaw, partial); const tendencies = deriveTendencies(baselineRaw, partial); profile = selectProfile(profile, previous, scores, stability, selectDominantTendency(tendencies)); }
  let selectedFinalAbility: Ability | null = null; if (data.finalRecord) { const equivalent = finalEquivalent(data.finalRecord.rawResult); if (!equivalent.ok) return equivalent; previous = { ...scores }; scores[equivalent.value.ability] = applyFinalScore(scores[equivalent.value.ability], equivalent.value.score); selectedFinalAbility = equivalent.value.ability; }
  const stability = calculateStability(baselineRaw, dailyRaw); const tendencies = deriveTendencies(baselineRaw, dailyRaw); const dominant = selectDominantTendency(tendencies); if (selectedFinalAbility) profile = selectProfile(profile, previous, scores, stability, dominant); else profile = { ...profile, profileVariantKey: selectProfile(profile, scores, scores, stability, dominant).profileVariantKey };
  const overallScore = deriveOverallScore(scores); if (!overallScore.ok) return overallScore;
  const hasAdditional = Object.fromEntries(ABILITIES.map((ability, index) => [ability, sorted.some((record) => record.analysisDay === index + 2) || selectedFinalAbility === ability])) as Record<Ability, boolean>; const condition = conditionMagnitudes(baselineRaw, dailyRaw, tendencies);
  return { ok: true, value: { calibrationVersion: CALIBRATION_VERSION, overallScoreVersion: OVERALL_SCORE_VERSION, overallScore: overallScore.value, scores, baselineScores: baseline.value, tendencies, dominantTendency: dominant, stability, profile, certifications: selectCertifications(scores), finalMetrics: { mostStable: mostStable(stability, hasAdditional), mostConditionSensitive: mostConditionSensitive(condition), mostPositivelyUpdated: mostPositivelyUpdated(baseline.value, scores, hasAdditional) }, crossInsights: selectCrossInsights(baseline.value, scores, stability, condition, hasAdditional), selectedFinalAbility } };
}
