import { describe, expect, it } from 'vitest';
import type { BalanceThreeWayTrial, BalanceTwoWayTrial, CenterTrial, ControlTrial, FocusTrial, SpatialMemoryTrial, TimeTrial } from '../assessment/trials';
import { normalizeBalance, normalizeCenter, normalizeControl, normalizeFocus, normalizeSpatialMemory, normalizeTimeSigned } from './normalizers';
import { applyFinalScore } from './scores';
import { applyDailyModifier } from './dailyModifier';
import { selectCertification } from './certification';
import { day7Confidence, selectDay7Target } from './finalSelector';
import { deriveBalanceConditionDegradation, mostConditionSensitive, mostPositivelyUpdated, mostStable } from './finalMetrics';
import { deriveTendencies, selectDominantTendency } from './tendencies';
import type { Day7Confidence, StabilityByAbility, Tendency } from './types';
const base={startedAtMs:0,completedAtMs:1,valid:true as const,invalidReason:null};
const time=(id:string,observed:number):TimeTrial=>({...base,trialId:id,kind:'time',condition:'baseline',targetDurationMs:3000,observedDurationMs:observed});
const scoreOf=(result:{ok:true;value:{score:number}}|{ok:false}):number=>result.ok?result.value.score:-1;
describe('assessment normalizers',()=>{
  it('TIME perfect와 signed dispersion을 계산하고 부족 근거를 거부한다',()=>{expect(scoreOf(normalizeTimeSigned([time('1',3000),time('2',3000)]))).toBe(100);expect(normalizeTimeSigned([time('1',2500)]).ok).toBe(false);expect(scoreOf(normalizeTimeSigned([time('1',2500),time('2',3500)]))).toBe(63);});
  it('CENTER 정중앙/거리, BALANCE two/three-way, CONTROL 분산을 계산한다',()=>{const centers:CenterTrial[]=[{...base,trialId:'c1',kind:'center',condition:'plain',shapeId:'square',target:{x:.5,y:.5},observed:{x:.5,y:.5}},{...base,trialId:'c2',kind:'center',condition:'plain',shapeId:'square',target:{x:.5,y:.5},observed:{x:.5,y:.5}}];expect(scoreOf(normalizeCenter(centers))).toBe(100);const balance:BalanceTwoWayTrial[]=[{...base,trialId:'b1',kind:'balanceTwoWay',orientation:'vertical',targetRatio:.5,observedRatio:.5},{...base,trialId:'b2',kind:'balanceTwoWay',orientation:'horizontal',targetRatio:.5,observedRatio:.5}];expect(scoreOf(normalizeBalance(balance))).toBe(100);const three:BalanceThreeWayTrial[]=[{...base,trialId:'x',kind:'balanceThreeWay',cutPositions:[1/3,2/3]},{...base,trialId:'y',kind:'balanceThreeWay',cutPositions:[1/3,2/3]}];expect(scoreOf(normalizeBalance(three))).toBe(100);const control:ControlTrial[]=[{...base,trialId:'k1',kind:'control',condition:'constant',targetPosition:.5,observedPosition:.5,speedNormalized:.5},{...base,trialId:'k2',kind:'control',condition:'constant',targetPosition:.5,observedPosition:.75,speedNormalized:.5}];expect(normalizeControl(control).ok).toBe(true);});
  it('FOCUS correctness/median RT와 all incorrect를 계산한다',()=>{const trial=(id:string,correct:boolean,rt:number|null):FocusTrial=>({...base,trialId:id,kind:'focus',condition:'visualSearch',stimulusId:id,correctTargetId:'a',selectedTargetId:correct?'a':'b',reactionTimeMs:rt,correct});expect(scoreOf(normalizeFocus([trial('1',true,1000),trial('2',true,3000),trial('3',true,2000)]))).toBe(90);expect(scoreOf(normalizeFocus([trial('1',false,1),trial('2',false,1)]))).toBe(0);});
  it('SPATIAL MEMORY deterministic minimum matching을 계산한다',()=>{const p=[{x:0,y:0},{x:1,y:0},{x:0,y:1}];const trials:SpatialMemoryTrial[]=[1,2].map(i=>({...base,trialId:String(i),kind:'spatialMemory',shownPositions:p,selectedPositions:[p[2]!,p[0]!,p[1]!],exposureDurationMs:1,responseTimeMs:1}));expect(scoreOf(normalizeSpatialMemory(trials))).toBe(100);});
  it('극단 finite TIME/FOCUS evidence를 throw 없이 정규화한다',()=>{expect(()=>normalizeTimeSigned([time('max1',Number.MAX_VALUE),time('max2',Number.MAX_VALUE)])).not.toThrow();const focus=(id:string):FocusTrial=>({...base,trialId:id,kind:'focus',condition:'visualSearch',stimulusId:id,correctTargetId:'a',selectedTargetId:'a',reactionTimeMs:Number.MAX_VALUE,correct:true});expect(()=>normalizeFocus([focus('max1'),focus('max2')])).not.toThrow();expect(scoreOf(normalizeTimeSigned([time('max1',Number.MAX_VALUE),time('max2',Number.MAX_VALUE)]))).toBe(25);expect(scoreOf(normalizeFocus([focus('max1'),focus('max2')]))).toBe(80);});
  it('Balance condition sensitivity를 terminal bias tendency와 분리한다',()=>{const baseline=(error:number):BalanceTwoWayTrial[]=>['vertical','horizontal'].map((orientation,index)=>({...base,trialId:`b${index}`,kind:'balanceTwoWay',orientation:orientation as 'vertical'|'horizontal',targetRatio:.5,observedRatio:.5+error}));const daily=(cuts:[number,number]):BalanceThreeWayTrial[]=>[1,2].map(index=>({...base,trialId:`d${index}`,kind:'balanceThreeWay',cutPositions:cuts}));const baselineResult={assessmentType:'day1_balance_two_way' as const,trials:baseline(.1)};const improvedResult={assessmentType:'day4_balance_three_way' as const,trials:daily([.2833333333333333,.5666666666666667])};expect(deriveBalanceConditionDegradation([baselineResult],[improvedResult])).toBe(0);const tendency=deriveTendencies([baselineResult],[improvedResult]).find(item=>item.key==='multiPartitionBias')!;expect(tendency.magnitude).toBeGreaterThan(0);const degradedResult={assessmentType:'day4_balance_three_way' as const,trials:daily([.18333333333333332,.5166666666666666])};expect(deriveBalanceConditionDegradation([{...baselineResult,trials:baseline(.02)}],[degradedResult])).toBeCloseTo(.4);expect(deriveBalanceConditionDegradation([{...baselineResult,trials:baseline(.11)}],[degradedResult])).toBe(0);});
});
describe('guardrails and selectors',()=>{
  it('DAILY V2 ±8과 FINAL ±6 cap',()=>{expect(applyDailyModifier(50,8)).toBe(58);expect(applyDailyModifier(50,-8)).toBe(42);expect(applyFinalScore(50,100)).toBe(56);expect(applyFinalScore(50,0)).toBe(44);});
  it.each([[54,'observer'],[55,'grade3'],[69,'grade3'],[70,'grade2'],[84,'grade2'],[85,'grade1'],[94,'grade1'],[95,'special']] as const)('cert %i => %s',(score,tier)=>expect(selectCertification(score)).toBe(tier));
  it('DAY7 unavailable과 fixed tie-break를 결정적으로 선택한다',()=>{const rows:Day7Confidence[]=['time','center','balance','control','focus'].map(ability=>({ability:ability as Day7Confidence['ability'],evidenceCoverage:1,conditionCoverage:1,stabilityAvailable:true,stability:.8}));expect(selectDay7Target(rows)).toBe('time');rows[2]={...rows[2]!,stabilityAvailable:false,stability:undefined};expect(selectDay7Target(rows)).toBe('balance');});
  it('DAY7 condition coverage는 assessment 존재가 아니라 valid condition minimum을 검사한다',()=>{const stability=Object.fromEntries(['time','center','balance','control','focus'].map(ability=>[ability,{stabilityAvailable:false,evidenceCount:0}])) as StabilityByAbility;const trials=[1,2,3].map(index=>({...base,trialId:`plain-${index}`,kind:'timeCondition' as const,condition:'plain' as const,targetDurationMs:3000 as const,observedDurationMs:3000}));const confidence=day7Confidence([],[{assessmentType:'day2_time_distraction',trials}],stability);expect(confidence.find(item=>item.ability==='time')?.conditionCoverage).toBe(0);});
  it('dominant tendency magnitude 동률은 registry 입력 순서를 유지한다',()=>{const items=[{key:'distractionSensitivity',magnitude:.2},{key:'visualBias',magnitude:.2}].map(x=>({...x,eligible:true,direction:'x',contentKey:'x',supportingEvidence:[]})) as Tendency[];expect(selectDominantTendency(items)?.key).toBe('distractionSensitivity');});
  it('final metric fallback과 delta 2/3 경계를 처리한다',()=>{expect(mostConditionSensitive({}).status).toBe('insufficientEvidence');expect(mostConditionSensitive({time:.09}).status).toBe('noClearConditionSensitivity');const unavailable={time:{stabilityAvailable:false,evidenceCount:1},center:{stabilityAvailable:false,evidenceCount:1},balance:{stabilityAvailable:false,evidenceCount:1},control:{stabilityAvailable:false,evidenceCount:1},focus:{stabilityAvailable:false,evidenceCount:1}} satisfies StabilityByAbility;const extra={time:true,center:false,balance:false,control:false,focus:false};expect(mostStable(unavailable,extra).status).toBe('insufficientEvidence');const baseline={time:50,center:50,balance:50,control:50,focus:50};expect(mostPositivelyUpdated(baseline,{...baseline,time:52},extra).status).toBe('noClearPositiveUpdate');expect(mostPositivelyUpdated(baseline,{...baseline,time:53},extra).status).toBe('selected');});
});
