import type { Day1RawResult, DailyRawResult } from '../assessment/results';
import type { CenterConditionTrial, ControlConditionTrial, TimeConditionTrial } from '../assessment/trials';
import { BALANCE_ERROR_WORST, CENTER_DISTANCE_WORST, CONTROL_ERROR_WORST, TENDENCY_DISPLAY_THRESHOLD, TIME_ERROR_WORST_MS } from './calibration';
import { clamp01, clampRatio01, mean } from './math';
import { matchingMeanDistance, threeWayError, twoWayError } from './normalizers';
import type { Tendency } from './types';
const average = (values: number[]) => { const result = mean(values); return result.ok ? result.value : null; };
const timeConditionError = (trial: TimeConditionTrial) => trial.valid ? Math.abs(trial.observedDurationMs - trial.targetDurationMs) : 0;
const centerShift = (trial: CenterConditionTrial, plain: Extract<CenterConditionTrial, { valid: true }>) => trial.valid ? { x: trial.observed.x - plain.observed.x, y: trial.observed.y - plain.observed.y } : { x: 0, y: 0 };
const controlConditionError = (trial: ControlConditionTrial) => trial.valid ? Math.abs(trial.observedPosition - trial.targetPosition) : 0;
export function deriveTendencies(baseline: readonly Day1RawResult[], daily: readonly DailyRawResult[]): Tendency[] {
  const items: Tendency[] = []; const d2 = daily.find((r) => r.assessmentType === 'day2_time_distraction');
  if (d2?.assessmentType === 'day2_time_distraction') { const errors = (condition: 'plain'|'distracted') => d2.trials.filter((t) => t.valid && t.condition === condition).map(timeConditionError); const plain=average(errors('plain')), distracted=average(errors('distracted')); if (plain!==null&&distracted!==null) { const delta=distracted-plain, magnitude=clampRatio01(Math.abs(delta),TIME_ERROR_WORST_MS), direction=delta>0?'degraded':delta<0?'improved':'neutral'; items.push({key:'distractionSensitivity',magnitude,direction,eligible:direction!=='neutral'&&magnitude>=TENDENCY_DISPLAY_THRESHOLD,contentKey:`time.distraction.${direction}`,supportingEvidence:['day2_time_distraction']}); } }
  const d3=daily.find((r)=>r.assessmentType==='day3_decorated_center'); if(d3?.assessmentType==='day3_decorated_center'){const plain=d3.trials.find(t=>t.valid&&t.condition==='plain');const decorated=d3.trials.filter(t=>t.valid&&t.condition!=='plain');if(plain?.valid&&decorated.length===2){const shifts=decorated.map(t=>centerShift(t,plain));const magnitude=clamp01(average(shifts.map(v=>Math.hypot(v.x,v.y)))!/CENTER_DISTANCE_WORST);const v={x:average(shifts.map(s=>s.x))!,y:average(shifts.map(s=>s.y))!};const useX=Math.abs(v.x)>=Math.abs(v.y);const direction=useX?(v.x>=0?'right':'left'):(v.y>=0?'up':'down');items.push({key:'visualBias',magnitude,direction,eligible:magnitude>=TENDENCY_DISPLAY_THRESHOLD,contentKey:`center.visualBias.${direction}`,supportingEvidence:['day3_decorated_center']});}}
  const b=baseline.find(r=>r.assessmentType==='day1_balance_two_way'),d4=daily.find(r=>r.assessmentType==='day4_balance_three_way');if(b?.assessmentType==='day1_balance_two_way'&&d4?.assessmentType==='day4_balance_three_way'){const two=average(b.trials.map(twoWayError).filter((v):v is number=>v!==null)),three=average(d4.trials.map(threeWayError).filter((v):v is number=>v!==null));const terminal=average(d4.trials.filter(t=>t.valid).map(t=>1-t.cutPositions[1]-1/3));if(two!==null&&three!==null&&terminal!==null){const degradation=three-two,magnitude=clamp01(Math.max(Math.abs(degradation),Math.abs(terminal))/BALANCE_ERROR_WORST),direction=terminal<0?'terminalSmall':terminal>0?'terminalLarge':degradation>0?'generalDegradation':'generalImprovement';items.push({key:'multiPartitionBias',magnitude,direction,eligible:magnitude>=TENDENCY_DISPLAY_THRESHOLD,contentKey:`balance.multiPartition.${direction}`,supportingEvidence:['day1_balance_two_way','day4_balance_three_way']});}}
  const d5=daily.find(r=>r.assessmentType==='day5_control_surprise');if(d5?.assessmentType==='day5_control_surprise'){const errors=(c:'predictable'|'surprise')=>average(d5.trials.filter(t=>t.valid&&t.condition===c).map(controlConditionError));const p=errors('predictable'),s=errors('surprise');if(p!==null&&s!==null){const delta=s-p,magnitude=clamp01(Math.abs(delta)/CONTROL_ERROR_WORST),direction=delta>0?'degraded':'improved';items.push({key:'surpriseSensitivity',magnitude,direction,eligible:delta!==0&&magnitude>=TENDENCY_DISPLAY_THRESHOLD,contentKey:`control.surprise.${direction}`,supportingEvidence:['day5_control_surprise']});}}
  const d6=daily.find(r=>r.assessmentType==='day6_spatial_memory');if(d6?.assessmentType==='day6_spatial_memory'){const distance=average(d6.trials.map(matchingMeanDistance).filter((v):v is number=>v!==null));if(distance!==null){const quality=1-clamp01(distance/0.35),magnitude=clamp01(Math.abs(quality-.5)*2),direction=quality>=.5?'supportive':'fragile';items.push({key:'spatialMemorySupport',magnitude,direction,eligible:magnitude>=TENDENCY_DISPLAY_THRESHOLD,contentKey:`focus.spatialMemory.${direction}`,supportingEvidence:['day6_spatial_memory']});}}
  const registry = ['distractionSensitivity','visualBias','multiPartitionBias','surpriseSensitivity','spatialMemorySupport'] as const;
  return registry.map((key) => items.find((item) => item.key === key) ?? { key, eligible: false, magnitude: 0, direction: 'unavailable', contentKey: `${key}.unavailable`, supportingEvidence: [] });
}
export const selectDominantTendency=(items:readonly Tendency[]):Tendency|null=>items.filter(i=>i.eligible).reduce<Tendency|null>((best,item)=>best===null||item.magnitude>best.magnitude?item:best,null);
