$ErrorActionPreference='Stop';$out='C:\Users\user\Downloads\day6-fast-reconstruction-26.0';New-Item -ItemType Directory -Force $out|Out-Null
$target=Invoke-RestMethod -Method Put 'http://127.0.0.1:9333/json/new?http://127.0.0.1:5174/artifacts/day6-fast-reconstruction-26.0/capture.html';$socket=[System.Net.WebSockets.ClientWebSocket]::new();$socket.ConnectAsync([Uri]$target.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$script:id=0
function Send($method,$params){$script:id++;$rid=$script:id;$json=@{id=$rid;method=$method;params=$params}|ConvertTo-Json -Depth 8 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($json);$socket.SendAsync([ArraySegment[byte]]$bytes,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult();while($true){$stream=[IO.MemoryStream]::new();do{$buffer=New-Object byte[] 1048576;$result=$socket.ReceiveAsync([ArraySegment[byte]]$buffer,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$stream.Write($buffer,0,$result.Count)}while(-not $result.EndOfMessage);$response=[Text.Encoding]::UTF8.GetString($stream.ToArray())|ConvertFrom-Json;if($response.id -eq $rid){return $response}}}
function Eval($expression){(Send 'Runtime.evaluate' @{expression=$expression;returnByValue=$true}).result.result.value}
function Click($selector){Eval("document.querySelector('$selector').click()")|Out-Null;Start-Sleep -Milliseconds 120}
function WaitFor($selector,$timeout=3000){$elapsed=0;while($elapsed-lt$timeout){if(Eval("!!document.querySelector('$selector')")){return};Start-Sleep -Milliseconds 25;$elapsed+=25};throw "Missing $selector"}
function Shot($name){Eval("document.querySelectorAll('.ait-panel-root,.ait-panel-toggle').forEach(e=>e.style.display='none')")|Out-Null;$shot=Send 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes("$out\$name.png",[Convert]::FromBase64String($shot.result.data));Eval("JSON.stringify((()=>{const d=document.documentElement,f=document.querySelector('.day6-memory-field')?.getBoundingClientRect(),cta=document.querySelector('.primary-button')?.getBoundingClientRect(),targets=document.querySelectorAll('.day6-memory-field .memory-target').length,selected=document.querySelectorAll('.day6-memory-field .memory-selected').length,lines=document.querySelectorAll('.memory-match-lines line').length;return{name:'$name',viewport:[innerWidth,innerHeight],documentHeight:d.scrollHeight,scrollWidth:d.scrollWidth,clientWidth:d.clientWidth,overflow:d.scrollWidth-d.clientWidth,field:f?{top:f.top,bottom:f.bottom,left:f.left,right:f.right,cropped:f.left<0||f.right>innerWidth}:null,cta:cta?{top:cta.top,bottom:cta.bottom,remaining:innerHeight-cta.bottom}:null,targets,selected,lines,phase:document.querySelector('.day6-assessment-poster')?.className||'analysis'}})())")}
function Point($x,$y){Eval("(()=>{const e=document.querySelector('[role=application]'),r=e.getBoundingClientRect();e.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:r.left+r.width*$x,clientY:r.top+r.height*$y}))})()")|Out-Null;Start-Sleep -Milliseconds 45}
function Navigate($w,$h){Send 'Emulation.setDeviceMetricsOverride' @{width=$w;height=$h;deviceScaleFactor=1;mobile=$true}|Out-Null;Send 'Page.navigate' @{url='http://127.0.0.1:5174/artifacts/day6-fast-reconstruction-26.0/capture.html'}|Out-Null;Start-Sleep -Milliseconds 650;Click '.home-screen .primary-button';Click '.daily-intro-screen .primary-button'}
function Flow($w,$h,$detailed){Navigate $w $h;Shot $(if($detailed){"01-ready-$($w)x$($h)"}else{"responsive-$w-ready"});Click '.day6-ready-action .primary-button';WaitFor '.is-exposure';Shot $(if($detailed){"02-exposure-spread-$($w)x$($h)"}else{"responsive-$w-exposure"});WaitFor '.is-blank' 1800;if($detailed){Shot "03-blank-$($w)x$($h)"};WaitFor '.is-recall';Shot $(if($detailed){"04-recall-$($w)x$($h)"}else{"responsive-$w-recall"});Point .20 .30;Point .70 .31;Point .51 .69;WaitFor '.day6-result-poster';Shot $(if($detailed){"05-result-spread-$($w)x$($h)"}else{"responsive-$w-result"});Click '.day6-result-action .primary-button';WaitFor '.is-exposure';if($detailed){Shot "06-exposure-clustered-$($w)x$($h)"};WaitFor '.is-recall' 1800;if($detailed){Shot "07-recall-clustered-$($w)x$($h)"};Point .35 .39;Point .61 .44;Point .49 .65;WaitFor '.day6-result-poster';Click '.day6-result-action .primary-button';Click '.summary-screen .primary-button';WaitFor '.day6-analysis';Shot "08-analysis-top-$($w)x$($h)";if($detailed){Eval('scrollTo(0,document.documentElement.scrollHeight)')|Out-Null;Start-Sleep -Milliseconds 120;Shot "09-analysis-bottom-$($w)x$($h)";$layout=Send 'Page.getLayoutMetrics' @{};$height=[Math]::Ceiling($layout.result.cssContentSize.height);$full=Send 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$true;clip=@{x=0;y=0;width=$w;height=$height;scale=1}};[IO.File]::WriteAllBytes("$out\analysis-full-$($w)x$($h).png",[Convert]::FromBase64String($full.result.data))}}
Send 'Page.enable' @{}|Out-Null;Flow 360 800 $true;Flow 412 786 $true;foreach($s in @(@{w=320;h=800},@{w=390;h=844},@{w=430;h=932})){Flow $s.w $s.h $false};$socket.Dispose()
