import { PrimaryButton } from '../../../components/PrimaryButton';
import type { DailyRawResult } from '../../../domain/assessment/results';
import type { LocalDateKey } from '../../../domain/progression/types';
import type { AnimationScheduler } from '../control/useControlAssessment';
import type { MeasurementClock } from '../time/useTimeTrial';
import { visualSkinClass } from '../visualSkin';
import { useDay5ControlAssessment } from './useDay5ControlAssessment';

interface Props { sessionDateKey: LocalDateKey; onComplete: (r: Extract<DailyRawResult, { assessmentType: 'day5_control_surprise' }>) => void; onDateInvalidated: () => void; clock?: MeasurementClock; dateNow?: () => Date; createTrialId?: () => string; animationScheduler?: AnimationScheduler; variationSessionId?: string }
const pct = (v: number) => `${(v * 100).toFixed(1)}%`;

export function Day5ControlAssessmentScreen(props: Props) {
  const a = useDay5ControlAssessment(props), { phase, trials, lastTrial } = a;
  if (phase === 'dateInvalidated') return <div className="screen analysis-error"><section role="alert"><h1>날짜가 변경되어 DAY 5를 다시 시작해야 합니다.</h1><p>DAY 1~4 기록은 그대로 유지됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>DAY 5 다시 시작</PrimaryButton></div></div>;
  if (phase === 'incomplete') return <div className="screen analysis-error"><section role="alert"><h1>추가 분석을 완료하지 못했습니다.</h1><p>이전 기록은 유지하고 DAY 5만 다시 시작합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>처음부터 다시</PrimaryButton></div></div>;
  if (phase === 'running') {
    return <div className="screen control-screen control-running day5-control-running"><header className="progress-header"><span>추가 분석 · 손가락 통제</span><span>{trials.length < 4 ? `${trials.length + 1} / 4` : `추가 측정 ${trials.length - 3}`}</span></header><section className="control-stage" aria-label="표시가 왼쪽에서 오른쪽으로 움직이고 있습니다. 목표 위치라고 느껴질 때 멈춰 버튼을 누르세요."><div className="day5-motion-signature"><div><span>MOTION CONTROL</span><strong>움직임 통제 측정</strong></div><p>MEASUREMENT IN PROGRESS</p></div><div className="day5-motion-register" aria-hidden="true"><span>START</span><i/><span>CONTROL RAIL</span><i/><span>TARGET</span></div><div className={`control-track ${visualSkinClass(props.variationSessionId, 'day5_control_surprise', trials.length)}`} aria-hidden="true"><span className="control-target" style={{ left: `${a.activeConfig.targetPosition * 100}%` }}/><span className="control-marker" style={{ left: `${a.markerPosition * 100}%` }}/></div><p>목표 위치에서 움직이는 점을 멈춰주세요.</p></section><div className="bottom-action"><PrimaryButton onClick={a.stopTrial}>멈춰!</PrimaryButton></div></div>;
  }
  if (phase === 'result' && lastTrial) return <div className="screen result-screen"><header className="progress-header"><span>추가 분석 · 손가락 통제</span><span>{Math.min(trials.length, 4)} / 4</span></header><section className="trial-result" aria-live="polite">{lastTrial.valid ? <><div className={`control-track control-result-track ${visualSkinClass(props.variationSessionId, 'day5_control_surprise', trials.length - 1)}`} aria-label="목표 위치와 멈춘 위치 비교"><span className="control-target" style={{ left: `${lastTrial.targetPosition * 100}%` }}/><span className="control-stop-marker" style={{ left: `${lastTrial.observedPosition * 100}%` }}/></div><h1>목표에서 {pct(Math.abs(lastTrial.observedPosition - lastTrial.targetPosition))} 벗어났어요.</h1><p>{lastTrial.condition === 'predictable' ? '예측 가능한 움직임' : '갑작스러운 변속'} 기록입니다.</p></> : <><h1>이번 측정은 제외됩니다.</h1><p role="alert">화면 상태가 바뀌거나 끝 지점을 놓쳐 다시 측정해야 합니다.</p></>}</section><div className="bottom-action"><PrimaryButton onClick={a.advanceFromResult}>{a.completion.status === 'completed' || a.completion.status === 'assessmentIncomplete' || a.completion.status === 'invalidAssessment' ? '결과 보기' : a.completion.status === 'retryAllowed' || !lastTrial.valid ? '다시 측정' : '다음 측정'}</PrimaryButton></div></div>;
  if (phase === 'complete') return <div className="screen summary-screen"><section className="summary-content"><p className="eyebrow">추가 측정 완료</p><h1>돌발 변속 측정을 마쳤습니다.</h1><p>예측 가능한 움직임과 갑작스러운 변속의 정지 오차를 비교합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={() => props.onComplete({ assessmentType: 'day5_control_surprise', trials })}>결과 확인</PrimaryButton></div></div>;
  return <div className="screen ready-screen"><header className="progress-header"><span>추가 분석 · 손가락 통제</span><span>1 / 4</span></header><section className="ready-content"><h1>목표 위치에서 움직이는 점을 멈춰주세요.</h1><p>움직임이 중간에 달라질 수 있어요.</p></section><div className="bottom-action"><PrimaryButton onClick={a.startTrial}>측정 시작</PrimaryButton></div></div>;
}
