import { act, renderHook } from '@testing-library/react';
import { afterEach, describe, expect, it } from 'vitest';
import type { AnimationScheduler } from '../control/useControlAssessment';
import { day5EndTimeSeconds } from './day5ControlMovement';
import { useDay5ControlAssessment } from './useDay5ControlAssessment';
class Scheduler implements AnimationScheduler { callbacks=new Map<number,FrameRequestCallback>();id=0;cancelled:number[]=[];request(c:FrameRequestCallback){this.callbacks.set(++this.id,c);return this.id;}cancel(id:number){this.cancelled.push(id);this.callbacks.delete(id);}frame(){const callbacks=[...this.callbacks.values()];this.callbacks.clear();callbacks.forEach(fn=>fn(0));} }
function setup(){let now=100,day=15,id=0;const scheduler=new Scheduler();const options={sessionDateKey:'2026-08-15' as const,clock:{now:()=>now},dateNow:()=>new Date(2026,7,day),createTrialId:()=>`t${++id}`,animationScheduler:scheduler};const hook=renderHook(()=>useDay5ControlAssessment(options));return{...hook,scheduler,setNow:(value:number)=>{now=value;},setDay:(value:number)=>{day=value;}};}
afterEach(()=>Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'}));
describe('useDay5ControlAssessment',()=>{
  it('stop clock의 piecewise position을 raw로 만들고 duplicate를 막는다',()=>{const t=setup();act(()=>t.result.current.startTrial());t.setNow(1100);act(()=>{t.result.current.stopTrial();t.result.current.stopTrial();});expect(t.result.current.trials).toHaveLength(1);expect(t.result.current.lastTrial).toMatchObject({condition:'predictable',targetPosition:.58,initialSpeedNormalized:.32,finalSpeedNormalized:.32,speedChangeAtNormalizedTime:null,observedPosition:.4,valid:true});});
  it('첫 3 trial과 4번째 completion trial 모두 result를 거친다',()=>{const t=setup();let now=100;for(const[index,elapsed]of[1562.5,1500,1500,2000].entries()){act(()=>t.result.current.startTrial());now+=elapsed;t.setNow(now);act(()=>t.result.current.stopTrial());expect(t.result.current.phase).toBe('result');if(index<3)act(()=>t.result.current.advanceFromResult());}expect(t.result.current.completion.status).toBe('completed');expect(t.result.current.trials.map(x=>x.condition)).toEqual(['predictable','surprise','predictable','surprise']);act(()=>{t.result.current.advanceFromResult();t.result.current.advanceFromResult();});expect(t.result.current.phase).toBe('complete');expect(t.result.current.trials).toHaveLength(4);});
  it.each([5,6,7])('attempt %i에서 completion되어도 마지막 result 뒤 complete한다',(completionAttempt)=>{const t=setup();let now=100;for(let attempt=1;attempt<=completionAttempt;attempt+=1){act(()=>t.result.current.startTrial());const config=t.result.current.activeConfig;const valid=attempt===2||attempt===3||attempt===completionAttempt;now+=valid?1000:day5EndTimeSeconds(config)*1000;t.setNow(now);act(()=>t.result.current.stopTrial());expect(t.result.current.phase).toBe('result');if(attempt<completionAttempt)act(()=>t.result.current.advanceFromResult());}expect(t.result.current.completion.status).toBe('completed');expect(t.result.current.trials).toHaveLength(completionAttempt);act(()=>t.result.current.advanceFromResult());expect(t.result.current.phase).toBe('complete');expect(t.result.current.trials).toHaveLength(completionAttempt);});
  it('end 전은 valid, exact end는 invalid다',()=>{const before=setup();act(()=>before.result.current.startTrial());before.setNow(100+day5EndTimeSeconds(before.result.current.activeConfig)*1000-.001);act(()=>before.result.current.stopTrial());expect(before.result.current.lastTrial?.valid).toBe(true);const exact=setup();act(()=>exact.result.current.startTrial());exact.setNow(100+day5EndTimeSeconds(exact.result.current.activeConfig)*1000);act(()=>exact.result.current.stopTrial());expect(exact.result.current.lastTrial).toMatchObject({valid:false,invalidReason:'insufficientObservation'});});
  it('background/date race는 하나의 dateChanged로 끝낸다',()=>{const t=setup();act(()=>t.result.current.startTrial());t.setDay(16);Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});act(()=>{document.dispatchEvent(new Event('visibilitychange'));t.scheduler.frame();t.result.current.stopTrial();});expect(t.result.current.trials).toHaveLength(1);expect(t.result.current.lastTrial).toMatchObject({valid:false,invalidReason:'dateChanged'});expect(t.result.current.phase).toBe('dateInvalidated');});
  it('이전 trial의 stale RAF는 다음 trial을 변경하거나 새 frame을 예약하지 않는다',()=>{const t=setup();act(()=>t.result.current.startTrial());const stale=t.scheduler.callbacks.get(t.scheduler.id)!;act(()=>t.result.current.stopTrial());act(()=>t.result.current.startTrial());const marker=t.result.current.markerPosition,scheduled=t.scheduler.callbacks.size;t.setNow(600);act(()=>stale(0));expect(t.result.current.markerPosition).toBe(marker);expect(t.scheduler.callbacks.size).toBe(scheduled);expect(t.result.current.trials).toHaveLength(1);act(()=>t.scheduler.frame());expect(t.result.current.markerPosition).toBeGreaterThan(marker);expect(t.result.current.trials).toHaveLength(1);});
  it('unmount는 RAF를 정리한다',()=>{const t=setup();act(()=>t.result.current.startTrial());const id=t.scheduler.id;t.unmount();expect(t.scheduler.cancelled).toContain(id);});
});
