import { useRef } from 'react';
import { PrimaryButton } from '../../../components/PrimaryButton';
import type { DailyRawResult } from '../../../domain/assessment/results';
import type { LocalDateKey } from '../../../domain/progression/types';
import { threeWayError } from '../../../domain/scoring/normalizers';
import type { Day2MeasurementClock } from '../day2Time/useDay2TimeAssessment';
import { visualSkinClass } from '../visualSkin';
import { day4Segments } from './day4BalanceConfig';
import { horizontalPointerRatio } from './day4BalanceMeasurement';
import { useDay4BalanceAssessment } from './useDay4BalanceAssessment';

interface Props { sessionDateKey: LocalDateKey; onComplete:(result:Extract<DailyRawResult,{assessmentType:'day4_balance_three_way'}>)=>void; onDateInvalidated:()=>void; clock?:Day2MeasurementClock; dateNow?:()=>Date; createTrialId?:()=>string; variationSessionId?:string }
const pct=(value:number)=>`${(value*100).toFixed(1)}%`;
function Masthead({attempt}:{attempt:number}){return <><header className="day2-ready-masthead"><span className="day2-ready-back" aria-hidden="true">‹</span><div><strong>DAY 4</strong><h1>복합 분배 · 균형 비교</h1></div><span className="day2-ready-help" aria-hidden="true">?</span></header><ol className="day4-attempt-progress" aria-label="DAY 4 진행 단계">{['INTRO','1ST','2ND','ANALYSIS'].map((label,index)=><li className={index===0||index<attempt?'is-complete':index===attempt?'is-active':'is-pending'} key={label}><span>{index===0||index<attempt?'✓':''}</span><strong>{label}</strong></li>)}</ol></>}
function AttemptCard({attempt}:{attempt:number}){return <section className="day4-attempt-card"><span className="day4-partition-icon" aria-hidden="true"/><div><h2>세 구간 분배 · {attempt===1?'FIRST':'SECOND'}</h2><p>두 구분선을 움직이는 복합 분배 환경입니다.</p></div><aside><strong>{attempt} / 2</strong><small>측정 진행</small></aside></section>}
function PartitionField({cuts,result=false}:{cuts:readonly[number,number];result?:boolean}){return <div className={result?'day4-result-field':'day4-preview-field'} aria-hidden="true"><span className="day4-field-corners"/>{result&&<><i className="day4-target-line first"/><i className="day4-target-line second"/></>}<b style={{left:`${cuts[0]*100}%`}}/><b style={{left:`${cuts[1]*100}%`}}/></div>}

export function Day4BalanceAssessmentScreen(props:Props){
 const assessment=useDay4BalanceAssessment(props);const{phase,trials,lastTrial,cuts}=assessment;const activePointer=useRef<{pointerId:number;divider:0|1}|null>(null);
 const updatePointer=(event:React.PointerEvent<HTMLDivElement>)=>{const active=activePointer.current;if(!active||active.pointerId!==event.pointerId)return;const ratio=horizontalPointerRatio(event.clientX,event.currentTarget.getBoundingClientRect());if(ratio!==null)assessment.moveCut(active.divider,ratio)};
 const keyMove=(divider:0|1,key:string)=>{const delta=key==='ArrowLeft'?-.01:key==='ArrowRight' ? .01 : 0;if(delta)assessment.moveCut(divider,cuts[divider]+delta)};
 if(phase==='dateInvalidated'||phase==='incomplete')return <div className="screen analysis-error"><section role="alert"><h1>{phase==='dateInvalidated'?'날짜가 변경되어 DAY 4를 다시 시작해야 합니다.':'추가 분석을 완료하지 못했습니다.'}</h1><p>DAY 1~3 기록은 그대로 유지됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>DAY 4 다시 시작</PrimaryButton></div></div>;
 if(phase==='complete')return <div className="screen summary-screen"><section className="summary-content"><p className="eyebrow">추가 측정 완료</p><h1>복합 분배 측정을 마쳤습니다.</h1><p>두 구분선으로 나눈 결과를 기존 균형 감각과 비교합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={()=>props.onComplete({assessmentType:'day4_balance_three_way',trials})}>결과 확인</PrimaryButton></div></div>;
 if(phase==='running')return <div className="screen day4-assessment-poster day4-running-poster"><Masthead attempt={trials.length+1}/><AttemptCard attempt={trials.length+1}/><main><header><p>복잡해지면 균형 감각도 달라질까?</p><h2>세 구간이 같아 보이도록<br/>두 선을 움직여주세요</h2></header><div className="day4-segment-signature"><div><span>SEGMENT CALIBRATION</span><strong>3구간 분배</strong></div><p>THREE-WAY DISTRIBUTION</p></div><div className="day4-instrument-frame"><div className="day4-channel-index" aria-hidden="true"><span>A</span><span>B</span><span>C</span></div><span className="day4-field-corners" aria-hidden="true"/><div className={`day4-track ${visualSkinClass(props.variationSessionId,'day4_balance_three_way',trials.length)}`} onPointerMove={updatePointer} onPointerUp={e=>{if(activePointer.current?.pointerId===e.pointerId)activePointer.current=null}} onPointerCancel={()=>{activePointer.current=null}}><span className="day4-segment day4-segment-one" style={{width:`${cuts[0]*100}%`}}/><span className="day4-segment day4-segment-two" style={{left:`${cuts[0]*100}%`,width:`${(cuts[1]-cuts[0])*100}%`}}/><span className="day4-segment day4-segment-three" style={{left:`${cuts[1]*100}%`,width:`${(1-cuts[1])*100}%`}}/>{([0,1] as const).map(divider=><button key={divider} type="button" className={`day4-divider divider-${divider+1}`} style={{left:`${cuts[divider]*100}%`}} role="slider" aria-label={`${divider+1}번째 구분선`} aria-valuemin={1} aria-valuemax={99} aria-valuenow={Math.round(cuts[divider]*100)} onPointerDown={e=>{activePointer.current={pointerId:e.pointerId,divider};e.currentTarget.setPointerCapture(e.pointerId)}} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();keyMove(divider,e.key)}}}><i className="day4-divider-id" aria-hidden="true">{divider===0?'01':'02'}</i></button>)}</div></div><p className="day4-running-note">각 손잡이를 좌우로 움직여 조절할 수 있어요.</p></main><div className="day4-running-action"><PrimaryButton onClick={assessment.confirm}>이대로 나누기</PrimaryButton></div></div>;
 if(phase==='result'&&lastTrial){const valid=lastTrial.valid?lastTrial:null;const segments=valid?day4Segments(valid.cutPositions):null;const error=valid?threeWayError(valid):null;return <div className="screen day4-assessment-poster day4-result-poster"><Masthead attempt={trials.length}/><AttemptCard attempt={trials.length}/><main aria-live="polite">{valid&&segments&&error!==null?<><header className="day4-result-heading"><span>✓</span><p>측정 완료</p><h2>기준에서 평균 {pct(error)}</h2></header><PartitionField cuts={valid.cutPositions} result/><p className="day4-result-legend"><span>내 구분선</span><span>같은 분배 기준</span></p><div className="day4-result-values">{segments.map((value,index)=><div key={index}><small>{index+1}구간</small><strong>{pct(value)}</strong></div>)}</div></>:<><h2>이번 측정은 제외됩니다.</h2><p role="alert">화면 상태가 바뀌어 다시 측정해야 합니다.</p></>}</main><div className="day4-result-action"><PrimaryButton onClick={assessment.startTrial}>{assessment.completion.status==='retryAllowed'||!valid?'다시 측정':'다음 측정'}</PrimaryButton></div></div>}
 return <div className="screen day4-assessment-poster day4-ready-poster"><Masthead attempt={1}/><AttemptCard attempt={1}/><main><header><p>오늘의 질문</p><h2>복잡해지면 균형 감각도 달라질까?</h2><span>두 개의 선으로 세 구간을 나누어 비교합니다.</span></header><PartitionField cuts={[.23,.74]}/><aside className="day4-ready-note"><strong>정답 안내 없이 시작합니다</strong><p>미리보기 구분선은 측정 목표와 관계없는 장식입니다.</p></aside></main><div className="day4-ready-action"><PrimaryButton onClick={assessment.startTrial}>측정 시작</PrimaryButton></div></div>;
}
