import { useRef } from 'react';
import { PrimaryButton } from '../../../components/PrimaryButton';
import type { DailyRawResult } from '../../../domain/assessment/results';
import type { LocalDateKey } from '../../../domain/progression/types';
import type { Day2MeasurementClock } from '../day2Time/useDay2TimeAssessment';
import { day4Segments } from './day4BalanceConfig';
import { horizontalPointerRatio } from './day4BalanceMeasurement';
import { useDay4BalanceAssessment } from './useDay4BalanceAssessment';
import { visualSkinClass } from '../visualSkin';
interface Props { sessionDateKey: LocalDateKey; onComplete: (result: Extract<DailyRawResult, { assessmentType: 'day4_balance_three_way' }>) => void; onDateInvalidated: () => void; clock?: Day2MeasurementClock; dateNow?: () => Date; createTrialId?: () => string; variationSessionId?: string }
const pct = (value: number) => `${Math.round(value * 100)}%`;
export function Day4BalanceAssessmentScreen(props: Props) {
  const assessment = useDay4BalanceAssessment(props); const { phase, trials, lastTrial, cuts } = assessment;
  const activePointer = useRef<{ pointerId: number; divider: 0 | 1 } | null>(null);
  const updatePointer = (event: React.PointerEvent<HTMLDivElement>) => { const active = activePointer.current; if (!active || active.pointerId !== event.pointerId) return; const ratio = horizontalPointerRatio(event.clientX, event.currentTarget.getBoundingClientRect()); if (ratio !== null) assessment.moveCut(active.divider, ratio); };
  const keyMove = (divider: 0 | 1, key: string) => { const delta = key === 'ArrowLeft' ? -.01 : key === 'ArrowRight' ? .01 : 0; if (delta) assessment.moveCut(divider, cuts[divider] + delta); };
  if (phase === 'dateInvalidated') return <div className="screen analysis-error"><section role="alert"><h1>날짜가 변경되어 추가 분석을 다시 시작해야 합니다.</h1><p>DAY 1~3 기록은 그대로 유지됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>DAY 4 다시 시작</PrimaryButton></div></div>;
  if (phase === 'incomplete') return <div className="screen analysis-error"><section role="alert"><h1>추가 분석을 완료하지 못했습니다.</h1><p>이전 분석은 유지하고 DAY 4만 다시 시작합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>처음부터 다시</PrimaryButton></div></div>;
  if (phase === 'complete') return <div className="screen summary-screen"><section className="summary-content"><p className="eyebrow">추가 측정 완료</p><h1>세 구간 분배를 마쳤습니다.</h1><p>단순한 2등분과 세 구간 분배의 차이를 비교합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={() => props.onComplete({ assessmentType: 'day4_balance_three_way', trials })}>결과 확인</PrimaryButton></div></div>;
  if (phase === 'running') return <div className="screen balance-screen day4-balance-running"><header className="progress-header"><span>추가 분석 · 균형 분배</span><span>{Math.min(trials.length + 1, 2)} / 2</span></header><section className="day4-balance-stage"><h1>세 구간이 같아 보이도록 나눠주세요.</h1><div className={`day4-track ${visualSkinClass(props.variationSessionId, 'day4_balance_three_way', trials.length)}`} onPointerMove={updatePointer} onPointerUp={(e) => { if (activePointer.current?.pointerId === e.pointerId) activePointer.current = null; }} onPointerCancel={() => { activePointer.current = null; }}><span className="day4-segment day4-segment-one" style={{ width: `${cuts[0] * 100}%` }} /><span className="day4-segment day4-segment-two" style={{ left: `${cuts[0] * 100}%`, width: `${(cuts[1] - cuts[0]) * 100}%` }} /><span className="day4-segment day4-segment-three" style={{ left: `${cuts[1] * 100}%`, width: `${(1 - cuts[1]) * 100}%` }} />{([0, 1] as const).map((divider) => <button key={divider} type="button" className="day4-divider" style={{ left: `${cuts[divider] * 100}%` }} role="slider" aria-label={`${divider + 1}번째 구분선`} aria-valuemin={1} aria-valuemax={99} aria-valuenow={Math.round(cuts[divider] * 100)} onPointerDown={(e) => { activePointer.current = { pointerId: e.pointerId, divider }; e.currentTarget.setPointerCapture(e.pointerId); }} onKeyDown={(e) => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); keyMove(divider, e.key); } }} />)}</div><p>두 선을 각각 움직일 수 있어요.</p></section><div className="bottom-action"><PrimaryButton onClick={assessment.confirm}>이대로 나누기</PrimaryButton></div></div>;
  if (phase === 'result' && lastTrial) { const segments = lastTrial.valid ? day4Segments(lastTrial.cutPositions) : null; return <div className="screen result-screen"><header className="progress-header"><span>추가 분석 · 균형 분배</span><span>{Math.min(trials.length, 2)} / 2</span></header><section className="trial-result" aria-live="polite">{segments ? <><h1>{segments.map(pct).join(' · ')}</h1><p>이번에 나눈 세 구간의 비율이에요.</p></> : <><h1>이번 측정은 제외됩니다.</h1><p role="alert">화면 상태가 바뀌어 다시 측정해야 합니다.</p></>}</section><div className="bottom-action"><PrimaryButton onClick={assessment.startTrial}>{assessment.completion.status === 'retryAllowed' || !lastTrial.valid ? '다시 측정' : '다음 측정'}</PrimaryButton></div></div>; }
  return <div className="screen ready-screen"><header className="progress-header"><span>추가 분석 · 균형 분배</span><span>1 / 2</span></header><section className="ready-content"><h1>두 선으로 세 구간을 나눠주세요.</h1><p>정답 안내 없이 눈으로 같아 보이게 맞추면 됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={assessment.startTrial}>측정 시작</PrimaryButton></div></div>;
}
