import { act, renderHook } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { useDay4BalanceAssessment } from './useDay4BalanceAssessment';
function setup() { let now=0; let date=new Date('2026-08-15T12:00:00'); let id=0; const hook=renderHook(()=>useDay4BalanceAssessment({sessionDateKey:'2026-08-15',clock:{now:()=>now},dateNow:()=>date,createTrialId:()=>`d4-${++id}`})); return {...hook,setNow:(v:number)=>{now=v;},setDate:(v:string)=>{date=new Date(v);}}; }
afterEach(()=>vi.restoreAllMocks());
describe('useDay4BalanceAssessment',()=>{
  it('confirm 전에는 raw를 만들지 않고 double confirm도 하나만 저장한다',()=>{const {result,setNow}=setup();act(()=>result.current.startTrial());expect(result.current.cuts).toEqual([.28,.72]);act(()=>result.current.moveCut(0,.3));act(()=>result.current.moveCut(1,.65));expect(result.current.trials).toHaveLength(0);setNow(100);act(()=>{result.current.confirm();result.current.confirm();});expect(result.current.trials).toHaveLength(1);expect(result.current.trials[0]).toMatchObject({kind:'balanceThreeWay',cutPositions:[.3,.65],valid:true,startedAtMs:0,completedAtMs:100});});
  it('retry도 valid count가 아닌 전체 attempt A/B sequence를 사용한다',()=>{const {result}=setup();vi.spyOn(document,'visibilityState','get').mockReturnValue('hidden');const cuts:number[][]=[];for(let index=0;index<5;index+=1){act(()=>result.current.startTrial());cuts.push(result.current.cuts);act(()=>document.dispatchEvent(new Event('visibilitychange')));}expect(cuts).toEqual([[.28,.72],[.38,.62],[.28,.72],[.38,.62],[.28,.72]]);expect(result.current.phase).toBe('incomplete');});
  it('keyboard용 이동 helper가 crossing을 차단한다',()=>{const {result}=setup();act(()=>result.current.startTrial());act(()=>result.current.moveCut(0,.5));expect(result.current.cuts).toEqual([.5,.72]);act(()=>result.current.moveCut(0,.8));expect(result.current.cuts).toEqual([.5,.72]);act(()=>result.current.moveCut(1,.85));expect(result.current.cuts).toEqual([.5,.85]);});
  it('background/date 변경은 DAY 4 invalid evidence로만 처리한다',()=>{const {result,setDate}=setup();vi.spyOn(document,'visibilityState','get').mockReturnValue('hidden');act(()=>result.current.startTrial());act(()=>document.dispatchEvent(new Event('visibilitychange')));expect(result.current.trials[0]).toMatchObject({valid:false,invalidReason:'backgrounded'});act(()=>result.current.startTrial());setDate('2026-08-16T00:00:01');act(()=>document.dispatchEvent(new Event('visibilitychange')));expect(result.current.trials[1]).toMatchObject({valid:false,invalidReason:'dateChanged'});expect(result.current.phase).toBe('dateInvalidated');});
});
