import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import { App } from './App';
import { deriveAnalysis } from './domain/scoring/deriveAnalysis';
import type { DailyRecord, PersistedAppData } from './domain/storage/types';
import { MemoryStorageAdapter } from './infrastructure/storage/MemoryStorageAdapter';
import { baselineFixture } from './test/day1Fixture';
const day2: DailyRecord = { recordId:'d2',sessionId:'d2',analysisDay:2,assessmentType:'day2_time_distraction',startedAt:'2026-08-13T01:00:00Z',completedAt:'2026-08-13T01:01:00Z',localDateKey:'2026-08-13',rawResult:{assessmentType:'day2_time_distraction',trials:['plain','distracted','plain','distracted'].map((condition,index)=>({kind:'timeCondition' as const,condition:condition as 'plain'|'distracted',targetDurationMs:3000 as const,observedDurationMs:3000,trialId:`t${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}};
const root: PersistedAppData = { schemaVersion:1,baseline:baselineFixture,dailyRecords:[day2],metadata:{} };
const rect = { left:0,top:0,width:200,height:100,right:200,bottom:100,x:0,y:0,toJSON:()=>({}) };
async function completeDay3() { fireEvent.click(await screen.findByRole('button',{name:'오늘의 추가 분석'})); fireEvent.click(screen.getByRole('button',{name:'추가 분석 시작'})); fireEvent.click(screen.getByRole('button',{name:'측정 시작'})); for(let index=0;index<3;index+=1){const area=screen.getByRole('application',{name:'위치를 선택하는 영역'});Object.defineProperty(area,'getBoundingClientRect',{configurable:true,value:()=>rect});fireEvent.pointerDown(area,{clientX:index===0?100:120,clientY:50});if(index<2)fireEvent.click(screen.getByRole('button',{name:'다음 측정'}));}fireEvent.click(screen.getByRole('button',{name:'결과 확인'}));}
describe('App DAY 3 persistence flow',()=>{
  it('DAY 2 뒤 DAY 3를 append하고 Center만 갱신해 심화 분석 2/5와 STATE D를 유지한다',async()=>{const storage=new MemoryStorageAdapter(root);const before=deriveAnalysis(root);render(<App storagePort={storage} bypassInitialLoad={false} dateNow={()=>new Date('2026-08-14T12:00:00Z')} createSessionId={()=> 'stable-d3'}/>);await completeDay3();expect(screen.getByText('심화 분석 2/5')).toBeInTheDocument();await waitFor(()=>expect(storage.peek()?.dailyRecords.map(r=>r.analysisDay)).toEqual([2,3]));const saved=storage.peek()!;expect(saved.baseline).toEqual(baselineFixture);expect(saved.dailyRecords[0]).toEqual(day2);expect(saved.dailyRecords[1]).toMatchObject({recordId:'stable-d3:day3',assessmentType:'day3_decorated_center',analysisDay:3});const after=deriveAnalysis(saved);expect(before.ok&&after.ok).toBe(true);if(before.ok&&after.ok){expect(after.value.scores.time).toBe(before.value.scores.time);expect(after.value.scores.balance).toBe(before.value.scores.balance);expect(after.value.scores.control).toBe(before.value.scores.control);expect(after.value.scores.focus).toBe(before.value.scores.focus);expect(Math.abs(after.value.scores.center-before.value.baselineScores.center)).toBeLessThanOrEqual(8);}fireEvent.click(screen.getByRole('button',{name:'홈으로'}));expect(screen.getByRole('heading',{name:'오늘의 추가 분석 완료'})).toBeInTheDocument();});
  it('저장 실패 후 같은 DAY 3 payload를 재저장하며 재측정하지 않는다',async()=>{const storage=new MemoryStorageAdapter(root);storage.fail('save');render(<App storagePort={storage} initialPersistedData={root} dateNow={()=>new Date('2026-08-14T12:00:00Z')} createSessionId={()=> 'retry-d3'}/>);await completeDay3();expect(await screen.findByText(/추가 분석을 저장하지 못했습니다/)).toBeInTheDocument();storage.recover('save');fireEvent.click(screen.getByRole('button',{name:'다시 저장'}));await waitFor(()=>expect(storage.peek()?.dailyRecords[1]?.recordId).toBe('retry-d3:day3'));expect(screen.getByText('오늘 새로 발견한 것')).toBeInTheDocument();});
  it('reload는 심화 분석 2/5를 복원하고 다음 날짜 DAY 4 intro를 연다',async()=>{const d3={recordId:'d3',sessionId:'d3',analysisDay:3 as const,assessmentType:'day3_decorated_center' as const,startedAt:'2026-08-14T01:00:00Z',completedAt:'2026-08-14T01:01:00Z',localDateKey:'2026-08-14' as const,rawResult:{assessmentType:'day3_decorated_center' as const,trials:(['plain','decoratedLeft','decoratedRight'] as const).map((condition,index)=>({kind:'centerCondition' as const,condition,decorationSide:(['none','left','right'] as const)[index]!,stimulusId:(['day3-plain-01','day3-left-01','day3-right-01'] as const)[index]!,target:{x:.5,y:.5},observed:{x:.5,y:.5},trialId:`c${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}};const data={...root,dailyRecords:[day2,d3]};render(<App initialPersistedData={data} dateNow={()=>new Date('2026-08-15T12:00:00Z')}/>);fireEvent.click(screen.getByRole('button',{name:'내 분석서 보기'}));expect(screen.getByText('심화 분석 2/5')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'홈으로'}));fireEvent.click(screen.getByRole('button',{name:'오늘의 추가 분석'}));expect(screen.getByRole('heading',{name:/셋으로 나누면/})).toBeInTheDocument();});
});
