import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import { App } from './App';
import { deriveAnalysis } from './domain/scoring/deriveAnalysis';
import type { DailyRecord, PersistedAppData } from './domain/storage/types';
import { MemoryStorageAdapter } from './infrastructure/storage/MemoryStorageAdapter';
import { baselineFixture } from './test/day1Fixture';
const d2:DailyRecord={recordId:'d2',sessionId:'d2',analysisDay:2,assessmentType:'day2_time_distraction',startedAt:'2026-08-13T01:00:00Z',completedAt:'2026-08-13T01:01:00Z',localDateKey:'2026-08-13',rawResult:{assessmentType:'day2_time_distraction',trials:['plain','distracted','plain','distracted'].map((condition,index)=>({kind:'timeCondition' as const,condition:condition as 'plain'|'distracted',targetDurationMs:3000 as const,observedDurationMs:3000,trialId:`t${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}};
const d3:DailyRecord={recordId:'d3',sessionId:'d3',analysisDay:3,assessmentType:'day3_decorated_center',startedAt:'2026-08-14T01:00:00Z',completedAt:'2026-08-14T01:01:00Z',localDateKey:'2026-08-14',rawResult:{assessmentType:'day3_decorated_center',trials:(['plain','decoratedLeft','decoratedRight'] as const).map((condition,index)=>({kind:'centerCondition' as const,condition,decorationSide:(['none','left','right'] as const)[index]!,stimulusId:(['day3-plain-01','day3-left-01','day3-right-01'] as const)[index]!,target:{x:.5,y:.5},observed:{x:.5,y:.5},trialId:`c${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}};
const root:PersistedAppData={schemaVersion:1,baseline:baselineFixture,dailyRecords:[d2,d3],metadata:{}};
async function completeDay4(){fireEvent.click(await screen.findByRole('button',{name:'오늘의 추가 분석'}));fireEvent.click(screen.getByRole('button',{name:'추가 분석 시작'}));fireEvent.click(screen.getByRole('button',{name:'측정 시작'}));fireEvent.click(screen.getByRole('button',{name:'이대로 나누기'}));fireEvent.click(screen.getByRole('button',{name:'다음 측정'}));fireEvent.click(screen.getByRole('button',{name:'이대로 나누기'}));fireEvent.click(screen.getByRole('button',{name:'결과 확인'}));}
describe('App DAY 4 persistence flow',()=>{
  it('DAY 4를 append하고 Balance만 갱신해 심화 분석 3/5와 STATE D를 유지한다',async()=>{const storage=new MemoryStorageAdapter(root);const before=deriveAnalysis(root);render(<App storagePort={storage} bypassInitialLoad={false} dateNow={()=>new Date('2026-08-15T12:00:00Z')} createSessionId={()=> 'stable-d4'}/>);await completeDay4();expect(screen.getByText('심화 분석 3/5')).toBeInTheDocument();await waitFor(()=>expect(storage.peek()?.dailyRecords.map(r=>r.analysisDay)).toEqual([2,3,4]));const saved=storage.peek()!;expect(saved.baseline).toEqual(baselineFixture);expect(saved.dailyRecords[0]).toEqual(d2);expect(saved.dailyRecords[1]).toEqual(d3);expect(saved.dailyRecords[2]).toMatchObject({recordId:'stable-d4:day4',analysisDay:4,assessmentType:'day4_balance_three_way',rawResult:{trials:[{cutPositions:[.28,.72]},{cutPositions:[.38,.62]}]}});const after=deriveAnalysis(saved);expect(before.ok&&after.ok).toBe(true);if(before.ok&&after.ok){expect(after.value.scores.time).toBe(before.value.scores.time);expect(after.value.scores.center).toBe(before.value.scores.center);expect(after.value.scores.control).toBe(before.value.scores.control);expect(after.value.scores.focus).toBe(before.value.scores.focus);}fireEvent.click(screen.getByRole('button',{name:'홈으로'}));expect(screen.getByRole('heading',{name:'오늘의 추가 분석 완료'})).toBeInTheDocument();});
  it('저장 실패 후 동일 DAY 4 record를 다시 저장하고 재측정하지 않는다',async()=>{const storage=new MemoryStorageAdapter(root);storage.fail('save');render(<App storagePort={storage} initialPersistedData={root} dateNow={()=>new Date('2026-08-15T12:00:00Z')} createSessionId={()=> 'retry-d4'}/>);await completeDay4();expect(await screen.findByText(/추가 분석을 저장하지 못했습니다/)).toBeInTheDocument();storage.recover('save');fireEvent.click(screen.getByRole('button',{name:'다시 저장'}));await waitFor(()=>expect(storage.peek()?.dailyRecords[2]?.recordId).toBe('retry-d4:day4'));expect(screen.getByText('오늘 새로 확인한 것')).toBeInTheDocument();});
  it('DAY 4 다음 유효 날짜에는 DAY 5 intro를 연다',()=>{const d4:DailyRecord={recordId:'d4',sessionId:'d4',analysisDay:4,assessmentType:'day4_balance_three_way',startedAt:'2026-08-15T01:00:00Z',completedAt:'2026-08-15T01:01:00Z',localDateKey:'2026-08-15',rawResult:{assessmentType:'day4_balance_three_way',trials:[.3,.4].map((cut1,index)=>({kind:'balanceThreeWay' as const,cutPositions:[cut1,.7] as [number,number],trialId:`b${index}`,startedAtMs:index,completedAtMs:index+1,valid:true as const,invalidReason:null}))}};render(<App initialPersistedData={{...root,dailyRecords:[d2,d3,d4]}} dateNow={()=>new Date('2026-08-16T12:00:00Z')}/>);fireEvent.click(screen.getByRole('button',{name:'오늘의 추가 분석'}));expect(screen.getByRole('heading',{name:/갑자기 속도가 바뀌면/})).toBeInTheDocument();});
});
