import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import { App } from './App';
import { deriveAnalysis } from './domain/scoring/deriveAnalysis';
import { MemoryStorageAdapter } from './infrastructure/storage/MemoryStorageAdapter';
import { throughDay4Fixture } from './test/dailyThroughDay4Fixture';
import { DAY5_CONTROL_TRIAL_CONFIGS } from './domain/assessment/day5ControlConfig';
import type { DailyRecord } from './domain/storage/types';
const scheduler={request:()=>1,cancel:()=>undefined};
async function complete(advance:()=>void){fireEvent.click(await screen.findByRole('button',{name:'오늘의 추가 분석'}));fireEvent.click(screen.getByRole('button',{name:'추가 분석 시작'}));fireEvent.click(screen.getByRole('button',{name:'측정 시작'}));for(let index=0;index<4;index++){advance();fireEvent.click(screen.getByRole('button',{name:'멈춰!'}));expect(screen.getByLabelText('목표 위치와 멈춘 위치 비교')).toBeInTheDocument();if(index<3)fireEvent.click(screen.getByRole('button',{name:'다음 측정'}));else{expect(screen.getByRole('heading',{name:/목표에서 \d+\.\d% 벗어났어요/})).toBeInTheDocument();const comparison=screen.getByLabelText('목표 위치와 멈춘 위치 비교');expect(comparison.querySelector('.control-target')).toHaveAttribute('style','left: 68%;');expect(comparison.querySelector('.control-stop-marker')?.getAttribute('style')).toMatch(/^left: \d+(?:\.\d+)?%;$/);fireEvent.click(screen.getByRole('button',{name:'결과 보기'}));}}expect(screen.getByRole('heading',{name:'돌발 변속 측정을 마쳤습니다.'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'결과 확인'}));}
describe('App DAY 5 persistence',()=>{
  it('analysisDay 5를 append하고 Control만 변경한다',async()=>{let now=0;const storage=new MemoryStorageAdapter(throughDay4Fixture),before=deriveAnalysis(throughDay4Fixture);render(<App storagePort={storage} bypassInitialLoad={false} dateNow={()=>new Date('2026-08-16T12:00:00Z')} createSessionId={()=> 'stable-d5'} day5Clock={{now:()=>now}} day5AnimationScheduler={scheduler}/>);await complete(()=>{now+=1000;});expect(screen.getByText('심화 분석 4/5')).toBeInTheDocument();await waitFor(()=>expect(storage.peek()?.dailyRecords.map(r=>r.analysisDay)).toEqual([2,3,4,5]));const saved=storage.peek()!,after=deriveAnalysis(saved);expect(saved.dailyRecords[3]).toMatchObject({recordId:'stable-d5:day5',assessmentType:'day5_control_surprise'});expect(saved.dailyRecords[3]?.rawResult.trials).toHaveLength(4);expect(before.ok&&after.ok).toBe(true);if(before.ok&&after.ok){expect(after.value.scores.time).toBe(before.value.scores.time);expect(after.value.scores.center).toBe(before.value.scores.center);expect(after.value.scores.balance).toBe(before.value.scores.balance);expect(after.value.scores.focus).toBe(before.value.scores.focus);expect(after.value.scores.control).toBe(94);}fireEvent.click(screen.getByRole('button',{name:'홈으로'}));expect(screen.getByRole('heading',{name:'오늘의 추가 분석 완료'})).toBeInTheDocument();});
  it('저장 실패 뒤 동일 record를 재저장한다',async()=>{let now=0;const storage=new MemoryStorageAdapter(throughDay4Fixture);storage.fail('save');render(<App storagePort={storage} initialPersistedData={throughDay4Fixture} dateNow={()=>new Date('2026-08-16T12:00:00Z')} createSessionId={()=> 'retry-d5'} day5Clock={{now:()=>now}} day5AnimationScheduler={scheduler}/>);await complete(()=>{now+=500;});expect(await screen.findByText(/추가 분석을 저장하지 못했습니다/)).toBeInTheDocument();storage.recover('save');fireEvent.click(screen.getByRole('button',{name:'다시 저장'}));await waitFor(()=>expect(storage.peek()?.dailyRecords[3]?.recordId).toBe('retry-d5:day5'));});
  it('다음 유효 날짜에 DAY 6 순간 위치 기억 intro를 연다',async()=>{const day5:DailyRecord={recordId:'d5',sessionId:'d5',analysisDay:5,assessmentType:'day5_control_surprise',startedAt:'2026-08-16T01:00:00Z',completedAt:'2026-08-16T01:01:00Z',localDateKey:'2026-08-16',rawResult:{assessmentType:'day5_control_surprise',trials:DAY5_CONTROL_TRIAL_CONFIGS.map((config,index)=>({...config,kind:'controlCondition' as const,trialId:`d5-${index}`,startedAtMs:index,completedAtMs:index+1,observedPosition:config.targetPosition,valid:true as const,invalidReason:null}))}};const persisted={...throughDay4Fixture,dailyRecords:[...throughDay4Fixture.dailyRecords,day5]};render(<App storagePort={new MemoryStorageAdapter(persisted)} bypassInitialLoad={false} dateNow={()=>new Date('2026-08-17T12:00:00Z')}/>);fireEvent.click(await screen.findByRole('button',{name:'오늘의 추가 분석'}));expect(screen.getByRole('heading',{name:/방금 본 위치/})).toBeInTheDocument();expect(screen.getByText('추가 분석 5 / 5')).toBeInTheDocument();});
});
