import { useCallback, useEffect, useRef, useState } from 'react';
import { PrimaryButton } from '../../../components/PrimaryButton';
import { validateCompletion } from '../../../domain/assessment/completion';
import { FINAL_BALANCE_KINDS, FINAL_BALANCE_THREE_WAY_CONFIG, FINAL_BALANCE_VERTICAL_INITIAL_RATIO, FINAL_CENTER_STIMULI, FINAL_CONTROL_CONFIGS, FINAL_FOCUS_KINDS, FINAL_FOCUS_MEMORY_POSITIONS, FINAL_FOCUS_VISUAL_CONFIG, FINAL_TIME_CONDITIONS, finalAssessmentTypeForAbility } from '../../../domain/assessment/finalCalibrationConfig';
import type { FinalRawResult } from '../../../domain/assessment/results';
import type { AnyTrial } from '../../../domain/assessment/trials';
import { validateTrial } from '../../../domain/assessment/validation';
import { toLocalDateKey } from '../../../domain/progression/localDate';
import type { LocalDateKey } from '../../../domain/progression/types';
import type { Ability } from '../../../domain/scoring/types';
import { normalizePointerPosition } from '../center/centerMeasurement';
import { Day2Particles } from '../day2Time/Day2Particles';
import { FocusShape } from '../focus/FocusShape';
import { moveDay4Cut } from '../day4Balance/day4BalanceMeasurement';
import { day5PositionAtElapsed, hasReachedDay5End } from '../day5Control/day5ControlMovement';
import { BalanceInstrument, CenterInstrument, ControlInstrument, FocusInstrument, InstrumentReadyContent, TimeInstrument } from '../AssessmentInstruments';
import { visualSkinClass } from '../visualSkin';
import { FinalCalibrationSeal } from './FinalCalibrationPresentation';
import { FINAL_ABILITY_LABELS } from './finalAbilityLabels';

type Phase = 'ready'|'running'|'exposure'|'blank'|'recall'|'result'|'complete'|'incomplete'|'dateInvalidated';
export interface FinalTimerScheduler { set:(callback:()=>void,delay:number)=>number; clear:(id:number)=>void }
export interface FinalFrameScheduler { request:(callback:FrameRequestCallback)=>number; cancel:(id:number)=>void }
interface Props { ability:Ability;sessionDateKey:LocalDateKey;dateNow?:()=>Date;clock?:{now:()=>number};timerScheduler?:FinalTimerScheduler;frameScheduler?:FinalFrameScheduler;onComplete:(result:FinalRawResult)=>void;onRestart:()=>void;variationSessionId?:string }
interface ActiveTrial { id:string;started:number }
interface PendingFocus { id:string;generation:number }
const defaultClock={now:()=>performance.now()};
const defaultTimers:FinalTimerScheduler={set:(callback,delay)=>window.setTimeout(callback,delay),clear:id=>window.clearTimeout(id)};
const defaultFrames:FinalFrameScheduler={request:callback=>requestAnimationFrame(callback),cancel:id=>cancelAnimationFrame(id)};
const finalInstrument=(ability:Ability)=>ability==='time'?<TimeInstrument/>:ability==='center'?<CenterInstrument/>:ability==='balance'?<BalanceInstrument/>:ability==='control'?<ControlInstrument/>:<FocusInstrument/>;

export function FinalCalibrationScreen({ability,sessionDateKey,dateNow=()=>new Date(),clock=defaultClock,timerScheduler=defaultTimers,frameScheduler=defaultFrames,onComplete,onRestart,variationSessionId}:Props){
  const[phase,setPhaseState]=useState<Phase>('ready');const[trials,setTrials]=useState<AnyTrial[]>([]);const[selected,setSelected]=useState<{x:number;y:number}[]>([]);const[ratio,setRatio]=useState(FINAL_BALANCE_VERTICAL_INITIAL_RATIO);const[cuts,setCuts]=useState<[number,number]>([FINAL_BALANCE_THREE_WAY_CONFIG.cut1,FINAL_BALANCE_THREE_WAY_CONFIG.cut2]);const[marker,setMarker]=useState<number>(FINAL_CONTROL_CONFIGS[0]!.startPosition);const[focusInteractive,setFocusInteractive]=useState(false);
  const phaseRef=useRef<Phase>('ready');const active=useRef<ActiveTrial|null>(null);const pendingFocus=useRef<PendingFocus|null>(null);const selectedRef=useRef<{x:number;y:number}[]>([]);const recallStarted=useRef<number|null>(null);const timer=useRef<number|null>(null);const frames=useRef<number[]>([]);const timerGeneration=useRef(0);const frameGeneration=useRef(0);const appendLocked=useRef(false);const completionLocked=useRef(false);
  const attempt=trials.length;const assessmentType=finalAssessmentTypeForAbility(ability);const setPhase=(next:Phase)=>{phaseRef.current=next;setPhaseState(next)};
  const skin=visualSkinClass(variationSessionId,assessmentType,attempt);
  const previousSkin=visualSkinClass(variationSessionId,assessmentType,Math.max(0,attempt-1));
  const result=useCallback(()=>({assessmentType,selectedAbility:ability,trials} as FinalRawResult),[ability,assessmentType,trials]);
  const clearTimer=useCallback(()=>{timerGeneration.current+=1;if(timer.current!==null)timerScheduler.clear(timer.current);timer.current=null},[timerScheduler]);
  const clearFrames=useCallback(()=>{frameGeneration.current+=1;for(const id of frames.current)frameScheduler.cancel(id);frames.current=[];pendingFocus.current=null;setFocusInteractive(false)},[frameScheduler]);
  const clearAsync=useCallback(()=>{clearTimer();clearFrames()},[clearFrames,clearTimer]);
  const append=useCallback((trial:AnyTrial)=>{if(appendLocked.current)return;appendLocked.current=true;clearAsync();active.current=null;setTrials(current=>[...current,trial]);setPhase('result')},[clearAsync]);
  const identity=useCallback(()=>active.current??(pendingFocus.current?{id:pendingFocus.current.id,started:clock.now()}:null),[clock]);
  const common=useCallback((current:ActiveTrial,valid:true|false)=>({trialId:current.id,startedAtMs:current.started,completedAtMs:clock.now(),valid,invalidReason:valid?null:undefined}),[clock]);
  const appendInvalid=useCallback((reason:'backgrounded'|'outOfBounds'|'insufficientObservation')=>{const current=identity();if(!current||appendLocked.current)return;const changed=toLocalDateKey(dateNow())!==sessionDateKey;if(changed){appendLocked.current=true;clearAsync();active.current=null;setPhase('dateInvalidated');return}const base={trialId:current.id,startedAtMs:current.started,completedAtMs:clock.now(),valid:false as const,invalidReason:reason};if(ability==='time')append({...base,kind:'timeCondition',condition:FINAL_TIME_CONDITIONS[attempt%3]!,targetDurationMs:3000});else if(ability==='center'){const c=FINAL_CENTER_STIMULI[attempt%3]!;append({...base,kind:'centerCondition',condition:c.condition,decorationSide:c.decorationSide,stimulusId:c.stimulusId,target:{x:.5,y:.5}})}else if(ability==='balance'){if(FINAL_BALANCE_KINDS[attempt%2]==='balanceTwoWay')append({...base,kind:'balanceTwoWay',orientation:'vertical',targetRatio:.5});else append({...base,kind:'balanceThreeWay'})}else if(ability==='control'){const c=FINAL_CONTROL_CONFIGS[attempt%3]!;append({...base,kind:'controlCondition',condition:c.condition,targetPosition:c.targetPosition,initialSpeedNormalized:c.initialSpeedNormalized,finalSpeedNormalized:c.finalSpeedNormalized,speedChangeAtNormalizedTime:c.speedChangeAtNormalizedTime})}else if(FINAL_FOCUS_KINDS[attempt%2]==='focus')append({...base,kind:'focus',condition:'visualSearch',stimulusId:FINAL_FOCUS_VISUAL_CONFIG.stimulusId,correctTargetId:FINAL_FOCUS_VISUAL_CONFIG.correctTargetId});else append({...base,kind:'spatialMemory',shownPositions:FINAL_FOCUS_MEMORY_POSITIONS.map(point=>({...point})),...(selectedRef.current.length?{selectedPositions:selectedRef.current}:{}),...(recallStarted.current===null?{}:{exposureDurationMs:1200,responseTimeMs:base.completedAtMs-recallStarted.current})})},[ability,append,attempt,clearAsync,clock,dateNow,identity,sessionDateKey]);
  const scheduleMemory=useCallback((id:string)=>{const generation=++timerGeneration.current;timer.current=timerScheduler.set(()=>{if(generation!==timerGeneration.current||active.current?.id!==id)return;setPhase('blank');timer.current=timerScheduler.set(()=>{if(generation!==timerGeneration.current||active.current?.id!==id)return;recallStarted.current=clock.now();setPhase('recall')},300)},1200)},[clock,timerScheduler]);
  const activateFocus=useCallback((id:string)=>{const generation=++frameGeneration.current;pendingFocus.current={id,generation};const first=frameScheduler.request(()=>{if(pendingFocus.current?.generation!==generation)return;const second=frameScheduler.request(()=>{if(pendingFocus.current?.generation!==generation)return;if(toLocalDateKey(dateNow())!==sessionDateKey){appendLocked.current=true;clearFrames();setPhase('dateInvalidated');return}active.current={id,started:clock.now()};pendingFocus.current=null;frames.current=[];setFocusInteractive(true)});frames.current=[second]});frames.current=[first]},[clearFrames,clock,dateNow,frameScheduler,sessionDateKey]);
  const start=useCallback(()=>{if(active.current||pendingFocus.current)return;if(toLocalDateKey(dateNow())!==sessionDateKey){setPhase('dateInvalidated');return}clearAsync();appendLocked.current=false;const id=crypto.randomUUID();selectedRef.current=[];setSelected([]);setRatio(FINAL_BALANCE_VERTICAL_INITIAL_RATIO);setCuts([FINAL_BALANCE_THREE_WAY_CONFIG.cut1,FINAL_BALANCE_THREE_WAY_CONFIG.cut2]);recallStarted.current=null;if(ability==='focus'&&FINAL_FOCUS_KINDS[attempt%2]==='spatialMemory'){active.current={id,started:clock.now()};setPhase('exposure');scheduleMemory(id);return}if(ability==='focus'){setPhase('running');activateFocus(id);return}active.current={id,started:clock.now()};if(ability==='control'){const config=FINAL_CONTROL_CONFIGS[attempt%3]!;setMarker(config.startPosition);const generation=++frameGeneration.current;const tick=()=>{const current=active.current;if(generation!==frameGeneration.current||current?.id!==id)return;const elapsed=clock.now()-current.started;if(hasReachedDay5End(config,elapsed)){setMarker(config.endPosition);appendInvalid('insufficientObservation');return}setMarker(day5PositionAtElapsed(config,elapsed));frames.current=[frameScheduler.request(tick)]};frames.current=[frameScheduler.request(tick)]}setPhase('running')},[ability,activateFocus,appendInvalid,attempt,clearAsync,clock,dateNow,frameScheduler,scheduleMemory,sessionDateKey]);
  const finish=useCallback((event?:React.PointerEvent<HTMLElement>)=>{const current=active.current;if(!current||appendLocked.current)return;if(toLocalDateKey(dateNow())!==sessionDateKey){appendLocked.current=true;clearAsync();active.current=null;setPhase('dateInvalidated');return}const base={...common(current,true),valid:true as const,invalidReason:null};if(ability==='time'){append({...base,kind:'timeCondition',condition:FINAL_TIME_CONDITIONS[attempt%3]!,targetDurationMs:3000,observedDurationMs:base.completedAtMs-base.startedAtMs});return}if(ability==='center'&&event){const normalized=normalizePointerPosition(event,event.currentTarget.getBoundingClientRect());if(!normalized.ok){appendInvalid('outOfBounds');return}const c=FINAL_CENTER_STIMULI[attempt%3]!;append({...base,kind:'centerCondition',condition:c.condition,decorationSide:c.decorationSide,stimulusId:c.stimulusId,target:{x:.5,y:.5},observed:normalized.point});return}if(ability==='balance'){const candidate:AnyTrial=FINAL_BALANCE_KINDS[attempt%2]==='balanceTwoWay'?{...base,kind:'balanceTwoWay',orientation:'vertical',targetRatio:.5,observedRatio:ratio}:{...base,kind:'balanceThreeWay',cutPositions:cuts};if(!validateTrial(candidate).ok){appendInvalid('outOfBounds');return}append(candidate);return}if(ability==='control'){const c=FINAL_CONTROL_CONFIGS[attempt%3]!,elapsed=base.completedAtMs-base.startedAtMs;if(hasReachedDay5End(c,elapsed)){appendInvalid('insufficientObservation');return}append({...base,kind:'controlCondition',condition:c.condition,targetPosition:c.targetPosition,initialSpeedNormalized:c.initialSpeedNormalized,finalSpeedNormalized:c.finalSpeedNormalized,speedChangeAtNormalizedTime:c.speedChangeAtNormalizedTime,observedPosition:day5PositionAtElapsed(c,elapsed)})}},[ability,append,appendInvalid,attempt,clearAsync,common,dateNow,ratio,cuts,sessionDateKey]);
  const chooseFocus=useCallback((id:string)=>{const current=active.current;if(!focusInteractive||!current||appendLocked.current)return;active.current=null;setFocusInteractive(false);if(toLocalDateKey(dateNow())!==sessionDateKey){appendLocked.current=true;clearAsync();setPhase('dateInvalidated');return}const completedAtMs=clock.now();append({trialId:current.id,startedAtMs:current.started,completedAtMs,valid:true,invalidReason:null,kind:'focus',condition:'visualSearch',stimulusId:FINAL_FOCUS_VISUAL_CONFIG.stimulusId,correctTargetId:FINAL_FOCUS_VISUAL_CONFIG.correctTargetId,selectedTargetId:id,reactionTimeMs:completedAtMs-current.started,correct:id===FINAL_FOCUS_VISUAL_CONFIG.correctTargetId})},[append,clearAsync,clock,dateNow,focusInteractive,sessionDateKey]);
  const recall=useCallback((event:React.PointerEvent<HTMLElement>)=>{const current=active.current;if(phaseRef.current!=='recall'||!current||appendLocked.current)return;if(toLocalDateKey(dateNow())!==sessionDateKey){appendLocked.current=true;clearAsync();active.current=null;setPhase('dateInvalidated');return}const normalized=normalizePointerPosition(event,event.currentTarget.getBoundingClientRect());if(!normalized.ok){appendInvalid('outOfBounds');return}if(selectedRef.current.length>=3)return;selectedRef.current=[...selectedRef.current,normalized.point];setSelected(selectedRef.current);if(selectedRef.current.length===3){const completedAtMs=clock.now();append({trialId:current.id,startedAtMs:current.started,completedAtMs,valid:true,invalidReason:null,kind:'spatialMemory',shownPositions:FINAL_FOCUS_MEMORY_POSITIONS.map(point=>({...point})),selectedPositions:selectedRef.current,exposureDurationMs:1200,responseTimeMs:completedAtMs-(recallStarted.current??completedAtMs)})}},[append,appendInvalid,clearAsync,clock,dateNow,sessionDateKey]);
  const advance=useCallback(()=>{if(phaseRef.current!=='result')return;const status=validateCompletion(result()).status;if(status==='completed')setPhase('complete');else if(status==='assessmentIncomplete'||status==='invalidAssessment')setPhase('incomplete');else start()},[result,start]);
  useEffect(()=>{const listener=()=>{if(document.visibilityState==='hidden'&&(active.current||pendingFocus.current))appendInvalid('backgrounded')};document.addEventListener('visibilitychange',listener);return()=>document.removeEventListener('visibilitychange',listener)},[appendInvalid]);
  useEffect(()=>()=>{clearAsync();active.current=null},[clearAsync]);
  const updateCut=(divider:0|1,value:number)=>setCuts(current=>moveDay4Cut(current,divider,value)??current);
  if(phase==='dateInvalidated'||phase==='incomplete')return <div className="screen final-calibration-screen analysis-error"><section role="alert"><h1>{phase==='dateInvalidated'?'날짜가 변경되어 최종 보정을 다시 시작해야 합니다.':'최종 보정을 완료하지 못했습니다.'}</h1><p>DAY 1~6 기록은 그대로 유지됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={onRestart}>최종 보정 다시 시작</PrimaryButton></div></div>;
  if(phase==='complete')return <div className="screen final-calibration-screen final-calibration-complete summary-screen"><section><FinalCalibrationSeal compact/><p className="final-record-mark">FINAL INPUT RECORDED</p><h1>최종 보정 측정을 마쳤습니다.</h1><p>{FINAL_ABILITY_LABELS[ability]}의 최종 입력이 기록되었습니다.</p></section><div className="bottom-action"><PrimaryButton onClick={()=>{if(completionLocked.current)return;completionLocked.current=true;clearAsync();onComplete(result())}}>최종 결과 확인</PrimaryButton></div></div>;
  if(phase==='result'){const last=trials.at(-1);return <div className={`screen final-calibration-screen final-calibration-result result-screen ${previousSkin}`}><header className="progress-header"><span>최종 보정 · {FINAL_ABILITY_LABELS[ability]}</span><span>{trials.length}</span></header><section className="trial-result" aria-live="polite"><p className="final-result-label">FINAL TRIAL RESULT</p><h1>{last?.valid?'이번 측정이 기록됐습니다.':'이번 측정은 제외됩니다.'}</h1>{last&&<FinalTrialDetails trial={last}/>}<span className="final-input-stamp" aria-hidden="true">최종 입력 확인</span></section><div className="bottom-action"><PrimaryButton onClick={advance}>{validateCompletion(result()).status==='completed'?'결과 보기':last?.valid?'다음 측정':'다시 측정'}</PrimaryButton></div></div>}
  if(phase==='exposure'||phase==='blank'||phase==='recall')return <div className="screen final-calibration-screen final-calibration-running day6-memory-screen"><header className="progress-header"><span>최종 보정 · 시각 집중</span><span>{attempt+1} / 2</span></header><section className={`memory-stage ${skin}`} role={phase==='recall'?'application':undefined} aria-label="기억 위치 선택" onPointerDown={recall}>{phase==='exposure'&&FINAL_FOCUS_MEMORY_POSITIONS.map((p,i)=><span key={i} className="memory-target" style={{left:`${p.x*100}%`,top:`${p.y*100}%`}}/>)}{phase==='recall'&&selected.map((p,i)=><span key={i} className="memory-selected" style={{left:`${p.x*100}%`,top:`${p.y*100}%`}}/>)}<p>{phase==='exposure'?'세 위치를 기억해 주세요.':phase==='blank'?'잠시만 기다려 주세요.':`${selected.length} / 3`}</p></section></div>;
  if(phase==='running'&&ability==='time')return <div className={`screen final-calibration-screen final-calibration-running running-screen ${skin} ${FINAL_TIME_CONDITIONS[attempt%3]==='distracted'?'is-distracted':''}`}><header className="progress-header"><span>최종 보정 · 시간 감각</span><span>{attempt+1} / 3</span></header>{FINAL_TIME_CONDITIONS[attempt%3]==='distracted'&&<Day2Particles/>}<section><h1>3초라고 느껴질 때 눌러주세요.</h1></section><div className="bottom-action"><PrimaryButton onClick={()=>finish()}>지금!</PrimaryButton></div></div>;
  if(phase==='running'&&ability==='center'){const stimulus=FINAL_CENTER_STIMULI[attempt%3]!;return <div className={`screen final-calibration-screen final-calibration-running center-screen center-running day3-center-running ${skin}`}><header className="progress-header"><span>최종 보정 · 중심 인지</span><span>{attempt+1} / 3</span></header><section className="center-stage"><div className="day3-center-area" role="application" aria-label="중심 선택" onPointerDown={finish}>{stimulus.circles.map((circle,index)=><span aria-hidden="true" className="day3-decoration" key={index} style={{left:`${circle.x*100}%`,top:`${circle.y*100}%`,width:`${circle.r*200}%`,aspectRatio:'1'}}/>)}</div><p>중심이라고 느껴지는 곳을 선택하세요.</p></section></div>}
  if(phase==='running'&&ability==='balance')return <div className={`screen final-calibration-screen final-calibration-running day4-balance-stage ${skin}`}><header className="progress-header"><span>최종 보정 · 균형 분배</span><span>{attempt+1} / 2</span></header><section><h1>{FINAL_BALANCE_KINDS[attempt%2]==='balanceTwoWay'?'세로선을 조절하세요.':'두 선으로 3등분하세요.'}</h1><div className="day4-track">{FINAL_BALANCE_KINDS[attempt%2]==='balanceTwoWay'?<input aria-label="세로 구분선" type="range" min="1" max="99" value={ratio*100} onChange={event=>setRatio(Number(event.target.value)/100)}/>:<><input aria-label="첫 구분선" type="range" min="1" max="99" value={cuts[0]*100} onChange={event=>updateCut(0,Number(event.target.value)/100)}/><input aria-label="두 번째 구분선" type="range" min="1" max="99" value={cuts[1]*100} onChange={event=>updateCut(1,Number(event.target.value)/100)}/></>}</div></section><div className="bottom-action"><PrimaryButton onClick={()=>finish()}>확정</PrimaryButton></div></div>;
  if(phase==='running'&&ability==='control'){const config=FINAL_CONTROL_CONFIGS[attempt%3]!;return <div className={`screen final-calibration-screen final-calibration-running control-screen control-running day5-control-running ${skin}`}><header className="progress-header"><span>최종 보정 · 손가락 통제</span><span>{attempt+1} / 3</span></header><section className="control-stage" aria-label="표시가 왼쪽에서 오른쪽으로 움직입니다."><div className="control-track" aria-hidden="true"><span className="control-target" style={{left:`${config.targetPosition*100}%`}}/><span className="control-marker" style={{left:`${marker*100}%`}}/></div><p>목표 위치에서 움직이는 점을 멈춰주세요.</p></section><div className="bottom-action"><PrimaryButton onClick={()=>finish()}>멈춰!</PrimaryButton></div></div>}
  if(phase==='running'&&ability==='focus')return <div className={`screen final-calibration-screen final-calibration-running focus-running ${skin}`}><header className="progress-header"><span>최종 보정 · 시각 집중</span><span>{attempt+1} / 2</span></header><section className="focus-grid">{FINAL_FOCUS_VISUAL_CONFIG.items.map(item=><button className="focus-item" key={item.id} aria-label={item.id} disabled={!focusInteractive} onClick={()=>chooseFocus(item.id)}><FocusShape shape={item.shape}/></button>)}</section></div>;
  return <div className="screen final-calibration-screen final-calibration-ready ready-screen"><div className="final-calibration-masthead"><FinalCalibrationSeal compact/><div><strong>FINAL CALIBRATION</strong><small>DAY 7 / 7 · 최종 정밀 보정</small></div></div><p className="final-selected-ability"><span>최종 보정 대상</span><strong>{FINAL_ABILITY_LABELS[ability]}</strong><small>SELECTED ABILITY</small></p><InstrumentReadyContent instrument={finalInstrument(ability)} eyebrow="최종 측정 준비 완료" title={`${FINAL_ABILITY_LABELS[ability]}을 한 번 더 확인합니다.`}>누적 기록에서 최종 확인이 가장 필요한 능력입니다.</InstrumentReadyContent><div className="bottom-action"><PrimaryButton onClick={start}>측정 시작</PrimaryButton></div></div>;
}

function FinalTrialDetails({trial}:{trial:AnyTrial}){if(!trial.valid)return <p role="alert">화면 상태를 확인할 수 없어 다시 측정해야 합니다.</p>;if(trial.kind==='timeCondition')return <p>목표 3,000ms · 실제 {Math.round(trial.observedDurationMs)}ms · 오차 {Math.round(Math.abs(trial.observedDurationMs-trial.targetDurationMs))}ms</p>;if(trial.kind==='centerCondition')return <p>실제 중심 50% / 50% · 선택 {(trial.observed.x*100).toFixed(1)}% / {(trial.observed.y*100).toFixed(1)}%</p>;if(trial.kind==='balanceTwoWay')return <p>목표 50.0% · 실제 {(trial.observedRatio*100).toFixed(1)}%</p>;if(trial.kind==='balanceThreeWay')return <p>실제 분배 {(trial.cutPositions[0]*100).toFixed(1)}% / {((trial.cutPositions[1]-trial.cutPositions[0])*100).toFixed(1)}% / {((1-trial.cutPositions[1])*100).toFixed(1)}%</p>;if(trial.kind==='controlCondition')return <p>목표 {(trial.targetPosition*100).toFixed(1)}% · 실제 {(trial.observedPosition*100).toFixed(1)}% · 오차 {(Math.abs(trial.observedPosition-trial.targetPosition)*100).toFixed(1)}%</p>;if(trial.kind==='focus')return <p>{trial.correct?'목표를 찾았어요.':'다른 항목을 선택했어요.'}{trial.reactionTimeMs===null?'':' · 반응 '+Math.round(trial.reactionTimeMs)+'ms'}</p>;if(trial.kind==='spatialMemory')return <p>기억한 위치 3개를 기록했어요.</p>;return null}
