$ErrorActionPreference = 'Stop'
$target = (Invoke-RestMethod 'http://127.0.0.1:9333/json/list')[0]
$socket = [System.Net.WebSockets.ClientWebSocket]::new()
$socket.ConnectAsync([Uri]$target.webSocketDebuggerUrl, [Threading.CancellationToken]::None).GetAwaiter().GetResult()
$script:id = 0
function Send-Cdp($method, $params) { $script:id++; $requestId=$script:id; $json=@{id=$requestId;method=$method;params=$params}|ConvertTo-Json -Depth 8 -Compress; $bytes=[Text.Encoding]::UTF8.GetBytes($json); $socket.SendAsync([ArraySegment[byte]]$bytes,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult(); while($true){$stream=[IO.MemoryStream]::new();do{$buffer=New-Object byte[] 1048576;$result=$socket.ReceiveAsync([ArraySegment[byte]]$buffer,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$stream.Write($buffer,0,$result.Count)}while(-not $result.EndOfMessage);$response=[Text.Encoding]::UTF8.GetString($stream.ToArray())|ConvertFrom-Json;if($response.id -eq $requestId){return $response}} }
function Click($selector){Send-Cdp 'Runtime.evaluate' @{expression="document.querySelector('$selector').click()"}|Out-Null;Start-Sleep -Milliseconds 120}
function Capture($name,$width,$height){Send-Cdp 'Emulation.setDeviceMetricsOverride' @{width=$width;height=$height;deviceScaleFactor=1;mobile=$true}|Out-Null;Start-Sleep -Milliseconds 200;Send-Cdp 'Runtime.evaluate' @{expression="document.querySelectorAll('.ait-panel-root,.ait-panel-toggle').forEach(element=>element.style.display='none')"}|Out-Null;$shot=Send-Cdp 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes("C:\Users\user\Downloads\day2-distracted-running-22.4\$name.png",[Convert]::FromBase64String($shot.result.data));$expression="JSON.stringify((()=>{const d=document.documentElement,b=document.querySelector('.day2-running-action .now-button').getBoundingClientRect(),i=document.querySelector('.day2-empty-dial').getBoundingClientRect(),p=document.querySelector('[data-testid=day2-particles]');return{viewport:[innerWidth,innerHeight],overflow:d.scrollWidth-d.clientWidth,documentHeight:d.scrollHeight,attempt:document.querySelector('.day2-running-condition aside').getAttribute('aria-label'),particles:p.children.length,reference:document.body.innerText.includes('3.000'),cta:{left:b.left,right:b.right,bottom:b.bottom},dial:{left:i.left,right:i.right}}})())";$metrics=Send-Cdp 'Runtime.evaluate' @{expression=$expression;returnByValue=$true};Write-Output "$name`: $($metrics.result.result.value)"}
New-Item -ItemType Directory -Force 'C:\Users\user\Downloads\day2-distracted-running-22.4'|Out-Null
Send-Cdp 'Page.enable' @{}|Out-Null;Send-Cdp 'Page.navigate' @{url='http://127.0.0.1:5174/artifacts/day2-distracted-running-22.4/capture.html'}|Out-Null;Start-Sleep -Milliseconds 800
Click '.primary-button';Click '.day2-ready-action .primary-button';Click '.day2-running-action .now-button';Click '.day2-result-action .primary-button'
Capture 'day2-distracted-first-360x800' 360 800;Capture 'day2-distracted-first-412x786' 412 786
Click '.day2-running-action .now-button';Click '.day2-result-action .primary-button';Click '.day2-running-action .now-button';Click '.day2-result-action .primary-button'
Capture 'day2-distracted-second-412x786' 412 786
$socket.Dispose()
