import { PrimaryButton } from '../../../components/PrimaryButton';
import type { DailyRawResult } from '../../../domain/assessment/results';
import type { LocalDateKey } from '../../../domain/progression/types';
import { centerDistanceError } from '../center/centerMeasurement';
import type { Day2MeasurementClock } from '../day2Time/useDay2TimeAssessment';
import { useDay3CenterAssessment } from './useDay3CenterAssessment';
import { visualSkinClass } from '../visualSkin';
interface Props { sessionDateKey: LocalDateKey; onComplete: (result: Extract<DailyRawResult, { assessmentType: 'day3_decorated_center' }>) => void; onDateInvalidated: () => void; clock?: Day2MeasurementClock; dateNow?: () => Date; createTrialId?: () => string; variationSessionId?: string }
const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
const opticalCondition = (condition: 'plain' | 'decoratedLeft' | 'decoratedRight') => condition === 'plain' ? { ko: '기준 시야', en: 'NEUTRAL FIELD', side: 'neutral' } : condition === 'decoratedLeft' ? { ko: '시각 편향', en: 'LEFT FIELD', side: 'left' } : { ko: '시각 편향', en: 'RIGHT FIELD', side: 'right' };
export function Day3CenterAssessmentScreen(props: Props) {
  const assessment = useDay3CenterAssessment(props); const { phase, trials, lastTrial, activeStimulus } = assessment;
  if (phase === 'dateInvalidated') return <div className="screen analysis-error"><section role="alert"><h1>날짜가 변경되어 추가 분석을 다시 시작해야 합니다.</h1><p>DAY 1과 DAY 2 기록은 그대로 유지됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>DAY 3 다시 시작</PrimaryButton></div></div>;
  if (phase === 'incomplete') return <div className="screen analysis-error"><section role="alert"><h1>추가 분석을 완료하지 못했습니다.</h1><p>이전 분석은 유지하고 DAY 3만 다시 시작합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>처음부터 다시</PrimaryButton></div></div>;
  if (phase === 'complete') return <div className="screen summary-screen"><section className="summary-content"><p className="eyebrow">추가 측정 완료</p><h1>시각 유도 측정을 마쳤습니다.</h1><p>무장식 상태와 주변 정보가 있을 때의 중심 판단을 비교합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={() => props.onComplete({ assessmentType: 'day3_decorated_center', trials })}>결과 확인</PrimaryButton></div></div>;
  if (phase === 'running' && activeStimulus) { const optical=opticalCondition(activeStimulus.condition);return <div className={`screen center-screen center-running day3-center-running optical-field-${optical.side}`}><header className="progress-header"><span>추가 분석 · 중심 감각</span><span>{Math.min(trials.length + 1, 3)} / 3</span></header><section className="center-stage"><div className="day3-optical-signature"><div><span>OPTICAL BIAS FIELD</span><strong>{optical.ko}</strong></div><p>{optical.en}</p></div><div className="day3-optical-rails" aria-hidden="true"><i/><i/></div><div className={`day3-center-area ${visualSkinClass(props.variationSessionId, 'day3_decorated_center', trials.length)}`} role="application" aria-label="위치를 선택하는 영역" aria-describedby="day3-center-instruction" onPointerDown={(event) => assessment.selectPosition(event, event.currentTarget.getBoundingClientRect())}>{activeStimulus.circles.map((circle, index) => <span aria-hidden="true" className="day3-decoration" key={index} style={{ left: `${circle.x * 100}%`, top: `${circle.y * 100}%`, width: `${circle.r * 200}%`, aspectRatio: '1' }} />)}</div><p id="day3-center-instruction">가운데라고 느끼는 위치를 눌러주세요.</p></section></div>;}
  if (phase === 'result' && lastTrial) return <div className="screen center-screen result-screen"><header className="progress-header"><span>추가 분석 · 중심 감각</span><span>{Math.min(trials.length, 3)} / 3</span></header><section className="trial-result" aria-live="polite">{lastTrial.valid ? <><div className={`day3-result-area ${visualSkinClass(props.variationSessionId, 'day3_decorated_center', trials.length - 1)}`} aria-hidden="true"><span className="center-marker actual-marker" /><span className="center-marker selected-marker" style={{ left: `${lastTrial.observed.x * 100}%`, top: `${lastTrial.observed.y * 100}%` }} /></div><p className="marker-legend"><span>선택한 점</span><span>실제 중심</span></p><h1>중심에서 {pct(centerDistanceError(lastTrial.observed))}</h1><p>{lastTrial.condition === 'plain' ? '무장식 조건' : lastTrial.condition === 'decoratedLeft' ? '왼쪽 장식 조건' : '오른쪽 장식 조건'}의 기록입니다.</p></> : <><h1>이번 측정은 제외됩니다.</h1><p role="alert">화면 상태를 확인할 수 없어 다시 측정해야 합니다.</p></>}</section><div className="bottom-action"><PrimaryButton onClick={assessment.startTrial}>{assessment.completion.status === 'retryAllowed' || !lastTrial.valid ? '다시 측정' : '다음 측정'}</PrimaryButton></div></div>;
  return <div className="screen ready-screen"><header className="progress-header"><span>추가 분석 · 중심 감각</span><span>1 / 3</span></header><section className="ready-content"><h1>가운데라고 느껴지는 곳을 눌러주세요.</h1><p>주변 장식은 따라가거나 누르지 않아도 됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={assessment.startTrial}>측정 시작</PrimaryButton></div></div>;
}
