import { PrimaryButton } from '../../../components/PrimaryButton';
import type { DailyRawResult } from '../../../domain/assessment/results';
import type { CenterCondition } from '../../../domain/assessment/trials';
import type { LocalDateKey } from '../../../domain/progression/types';
import { centerDistanceError } from '../center/centerMeasurement';
import type { Day2MeasurementClock } from '../day2Time/useDay2TimeAssessment';
import { useDay3CenterAssessment } from './useDay3CenterAssessment';
import { visualSkinClass } from '../visualSkin';
interface Props { sessionDateKey: LocalDateKey; onComplete: (result: Extract<DailyRawResult, { assessmentType: 'day3_decorated_center' }>) => void; onDateInvalidated: () => void; clock?: Day2MeasurementClock; dateNow?: () => Date; createTrialId?: () => string; variationSessionId?: string }
const pct=(v:number)=>`${(v*100).toFixed(1)}%`; const labels:Record<CenterCondition,string>={plain:'기본 조건 · PLAIN',decoratedLeft:'왼쪽 장식 · LEFT',decoratedRight:'오른쪽 장식 · RIGHT'};
const opticalCondition=(condition:CenterCondition)=>condition==='plain'?{ko:'기준 시야',en:'NEUTRAL FIELD',side:'neutral'}:condition==='decoratedLeft'?{ko:'시각 편향',en:'LEFT FIELD',side:'left'}:{ko:'시각 편향',en:'RIGHT FIELD',side:'right'};
function Masthead(){return <><header className="day2-ready-masthead"><span className="day2-ready-back" aria-hidden="true">‹</span><div><strong>DAY 3</strong><h1>시각 정보 · 중심 비교</h1></div><span className="day2-ready-help" aria-hidden="true">?</span></header><ol className="day3-condition-progress" aria-label="DAY 3 진행 단계">{['INTRO','PLAIN','LEFT','RIGHT','ANALYSIS'].map(x=><li key={x}><span/><strong>{x}</strong></li>)}</ol></>}
function ConditionCard({condition,attempt}:{condition:CenterCondition;attempt:number}){return <section className={`day3-condition-card is-${condition}`}><span className="day3-condition-optic" aria-hidden="true"/><div><h2>{labels[condition]}</h2><p>{condition==='plain'?'주변 장식이 없는 기준 환경입니다.':condition==='decoratedLeft'?'왼쪽에 시각 정보가 있는 환경입니다.':'오른쪽에 시각 정보가 있는 환경입니다.'}</p></div><aside><strong>{attempt} / 3</strong><small>측정 진행</small></aside></section>}
export function Day3CenterAssessmentScreen(props:Props){const assessment=useDay3CenterAssessment(props);const{phase,trials,lastTrial,activeStimulus}=assessment;
if(phase==='dateInvalidated'||phase==='incomplete')return <div className="screen analysis-error"><section role="alert"><h1>{phase==='dateInvalidated'?'날짜가 변경되어 추가 분석을 다시 시작해야 합니다.':'추가 분석을 완료하지 못했습니다.'}</h1><p>이전 분석은 그대로 유지됩니다.</p></section><div className="bottom-action"><PrimaryButton onClick={props.onDateInvalidated}>DAY 3 다시 시작</PrimaryButton></div></div>;
if(phase==='complete')return <div className="screen summary-screen"><section className="summary-content"><p className="eyebrow">추가 측정 완료</p><h1>시각 정보 비교를 마쳤습니다.</h1><p>세 조건에서의 중심 판단 차이를 분석합니다.</p></section><div className="bottom-action"><PrimaryButton onClick={()=>props.onComplete({assessmentType:'day3_decorated_center',trials})}>결과 확인</PrimaryButton></div></div>;
if(phase==='running'&&activeStimulus){const optical=opticalCondition(activeStimulus.condition);return <div className={`screen day3-assessment-poster day3-running-poster optical-field-${optical.side}`}><Masthead/><ConditionCard condition={activeStimulus.condition} attempt={trials.length+1}/><main><header><p>시각 정보에 얼마나 흔들릴까?</p><h2>가운데라고 느껴지는 곳을<br/>한 번 눌러주세요</h2></header><div className="day3-optical-signature"><div><span>OPTICAL BIAS FIELD</span><strong>{optical.ko}</strong></div><p>{optical.en}</p></div><div className="day3-optical-rails" aria-hidden="true"><i/><i/></div><div className="day3-optical-frame"><span className="day3-corners" aria-hidden="true"/><div className={`day3-center-area ${visualSkinClass(props.variationSessionId,'day3_decorated_center',trials.length)}`} role="application" aria-label="위치를 선택하는 영역" aria-describedby="day3-center-instruction" onPointerDown={e=>assessment.selectPosition(e,e.currentTarget.getBoundingClientRect())}>{activeStimulus.circles.map((c,i)=><span aria-hidden="true" className="day3-decoration" key={i} style={{left:`${c.x*100}%`,top:`${c.y*100}%`,width:`${c.r*200}%`,aspectRatio:'1'}}/>)}</div></div><p id="day3-center-instruction" className="day3-running-note">중심 안내선 없이 감각만으로 선택해 주세요.</p></main></div>}
if(phase==='result'&&lastTrial){const valid=lastTrial.valid?lastTrial:null;return <div className="screen day3-assessment-poster day3-result-poster"><Masthead/>{valid&&<ConditionCard condition={valid.condition} attempt={trials.length}/>}<main aria-live="polite">{valid?<><header className="day3-result-heading"><span>✓</span><p>측정 완료</p><h2>중심에서 {pct(centerDistanceError(valid.observed))}</h2></header><div className={`day3-result-field ${visualSkinClass(props.variationSessionId,'day3_decorated_center',trials.length-1)}`}><svg aria-hidden="true" viewBox="0 0 100 75" preserveAspectRatio="none"><line x1="50" y1="37.5" x2={valid.observed.x*100} y2={valid.observed.y*75}/></svg><span className="center-marker actual-marker"/><span className="center-marker selected-marker" style={{left:`${valid.observed.x*100}%`,top:`${valid.observed.y*100}%`}}/></div><p className="marker-legend"><span>선택한 점</span><span>실제 중심</span></p><aside className="day3-result-note"><strong>{labels[valid.condition]}</strong><p>선택 위치와 실제 중심의 거리를 표시했습니다.</p></aside></>:<><h2>이번 측정은 제외됩니다.</h2><p role="alert">화면 상태를 확인할 수 없어 다시 측정해야 합니다.</p></>}</main><div className="day3-result-action"><PrimaryButton onClick={assessment.startTrial}>{assessment.completion.status==='retryAllowed'||!valid?'다시 측정':'다음 측정'}</PrimaryButton></div></div>}
return <div className="screen day3-assessment-poster day3-ready-poster"><Masthead/><ConditionCard condition="plain" attempt={1}/><main><header><p>오늘의 질문</p><h2>시각 정보에 얼마나 흔들릴까?</h2><span>주변 정보가 달라질 때 중심 판단을 비교합니다.</span></header><div className="day3-optical-frame" aria-hidden="true"><span className="day3-corners"/><div className="day3-ready-field"/></div><aside className="day3-ready-note"><strong>중심 표시 없이 시작합니다</strong><p>장식은 선택 대상이 아니며, 가운데라고 느끼는 위치만 눌러주세요.</p></aside></main><div className="day3-ready-action"><PrimaryButton onClick={assessment.startTrial}>측정 시작</PrimaryButton></div></div>}
