$ErrorActionPreference='Stop';$target=(Invoke-RestMethod 'http://127.0.0.1:9333/json/list').Where({$_.type -eq 'page'},'First')[0];$socket=[System.Net.WebSockets.ClientWebSocket]::new();$socket.ConnectAsync([Uri]$target.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$script:id=0
function Send-Cdp($method,$params){$script:id++;$requestId=$script:id;$json=@{id=$requestId;method=$method;params=$params}|ConvertTo-Json -Depth 8 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($json);$socket.SendAsync([ArraySegment[byte]]$bytes,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult();while($true){$stream=[IO.MemoryStream]::new();do{$buffer=New-Object byte[] 1048576;$result=$socket.ReceiveAsync([ArraySegment[byte]]$buffer,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$stream.Write($buffer,0,$result.Count)}while(-not $result.EndOfMessage);$response=[Text.Encoding]::UTF8.GetString($stream.ToArray())|ConvertFrom-Json;if($response.id -eq $requestId){return $response}}}
function Eval($expression,$wait=140){Send-Cdp 'Runtime.evaluate' @{expression=$expression}|Out-Null;Start-Sleep -Milliseconds $wait}
function Shot($name,$width,$height){Eval "document.querySelectorAll('.ait-panel-root,.ait-panel-toggle').forEach(e=>e.style.display='none')" 40;$shot=Send-Cdp 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes("C:\Users\user\Downloads\day1-$width-$name.png",[Convert]::FromBase64String($shot.result.data));$expression="JSON.stringify({screen:'$name',overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,scrollY:scrollY,scrollHeight:document.documentElement.scrollHeight,viewport:innerHeight,buttons:Array.from(document.querySelectorAll('button')).filter(e=>{const r=e.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight}).length})";$response=Send-Cdp 'Runtime.evaluate' @{expression=$expression;returnByValue=$true};Write-Output "$width $($response.result.result.value)"}
function Center-Select(){Eval "(()=>{const e=document.querySelector('.center-shape'),r=e.getBoundingClientRect();e.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:r.left+r.width*.37,clientY:r.top+r.height*.33}))})()"}
function Run-Flow($width,$height){Send-Cdp 'Emulation.setDeviceMetricsOverride' @{width=$width;height=$height;deviceScaleFactor=1;mobile=$true}|Out-Null;Send-Cdp 'Page.navigate' @{url='http://127.0.0.1:5173/'}|Out-Null;Start-Sleep -Milliseconds 700;Eval "localStorage.clear();location.reload()" 700;Eval "window.__qaNow=0;Object.defineProperty(performance,'now',{configurable:true,value:()=>window.__qaNow})"
  Shot '01-home' $width $height;Eval "document.querySelector('.home-reference-cta').click()";Shot '02-intro' $width $height;Eval "document.querySelector('.intro-reference-start').click()";Shot '03-time-ready' $width $height;Eval "document.querySelector('.time-ready-reference-start').click()";Shot '04-time-running' $width $height;Eval "window.__qaNow=3100;document.querySelector('.time-running-action button').click()";Shot '05-time-result' $width $height
  Eval "document.querySelector('.time-result-poster .bottom-action button').click()";Eval "window.__qaNow=6150;document.querySelector('.time-running-action button').click()";Eval "document.querySelector('.time-result-poster .bottom-action button').click()";Eval "window.__qaNow=9150;document.querySelector('.time-running-action button').click()";Eval "document.querySelector('.summary-screen .bottom-action button').click()";Shot '06-center-ready' $width $height;Eval "document.querySelector('.center-ready-action button').click()";Shot '07-center-running' $width $height;Center-Select;Shot '08-center-result' $width $height
  Eval "document.querySelector('.center-result-poster .bottom-action button').click()";Center-Select;Eval "document.querySelector('.center-result-poster .bottom-action button').click()";Center-Select;Eval "document.querySelector('.summary-screen .bottom-action button').click()";Shot '09-balance-ready' $width $height;Eval "document.querySelector('.balance-ready-action button').click()";Shot '10-balance-running' $width $height;Eval "document.querySelector('.balance-running-action button').click()";Shot '11-balance-result' $width $height
  Eval "document.querySelector('.balance-result-action button').click()";Eval "document.querySelector('.balance-running-action button').click()";Eval "document.querySelector('.summary-screen .bottom-action button').click()";Shot '12-control-ready' $width $height;Eval "document.querySelector('.control-ready-action button').click()";Eval "window.__qaNow=9550" 180;Shot '13-control-running' $width $height;Eval "window.__qaNow=10150" 180;Shot '13b-control-running-later' $width $height;Eval "document.querySelector('.control-running-action button').click()";Shot '14-control-result' $width $height
  Eval "document.querySelector('.control-result-action button').click()";Eval "window.__qaNow=11400;document.querySelector('.control-running-action button').click()";Eval "document.querySelector('.control-result-action button').click()";Eval "window.__qaNow=12650;document.querySelector('.control-running-action button').click()";Eval "document.querySelector('.summary-screen .bottom-action button').click()";Shot '15-focus-ready' $width $height;Eval "document.querySelector('.focus-ready-action button').click()" 220;Shot '16-focus-running' $width $height;Eval "window.__qaNow=13492;document.querySelectorAll('.focus-item')[1].click()";Shot '17-focus-result' $width $height
  Eval "document.querySelector('.focus-result-action button').click()" 220;Eval "window.__qaNow=14496;document.querySelectorAll('.focus-item')[7].click()";Eval "document.querySelector('.focus-result-action button').click()" 220;Eval "window.__qaNow=15500;document.querySelectorAll('.focus-item')[10].click()";Eval "document.querySelector('.summary-screen .bottom-action button').click()" 350;Eval "scrollTo(0,0)";Shot '18-basic-top' $width $height;Eval "scrollTo(0,Math.max(0,(document.documentElement.scrollHeight-innerHeight)/2))";Shot '19-basic-middle' $width $height;Eval "scrollTo(0,document.documentElement.scrollHeight)";Shot '20-basic-bottom' $width $height
  $contamination="JSON.stringify({timeRunningReference:0,centerRunningGuides:0,balanceRunningFifty:0,controlRunningMetrics:0,focusRunningResultClasses:0,recordId:document.querySelector('[data-record-id]')?.getAttribute('data-record-id')||null})";Write-Output "$width completed"
}
Send-Cdp 'Page.enable' @{}|Out-Null;Run-Flow 360 800;Run-Flow 412 786;$socket.Dispose()
